/**
 * egdesk.schema.ts — committed seed schema
 *
 * COMMIT THIS FILE TO GIT.
 *
 * When someone opens this project in their EGDesk, these tables are created
 * automatically in their dev database on first server start.
 *
 * Unlike egdesk.config.ts (auto-generated, gitignored), this file is the
 * portable source of truth for your app's database structure.
 *
 * Edit this file when you add/remove tables or columns. Do NOT edit
 * egdesk.config.ts — EGDesk regenerates it from the live database.
 */

export const COLUMN_DEFINITIONS = {
  crm_customers: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'phone', type: 'TEXT', notNull: true },
    { name: 'email', type: 'TEXT' },
    { name: 'tags', type: 'TEXT' },
    { name: 'memo', type: 'TEXT' },
    { name: 'address', type: 'TEXT' },
    { name: 'shipping_address', type: 'TEXT' },
    { name: 'recipient_name', type: 'TEXT' },
    { name: 'recipient_phone', type: 'TEXT' },
    { name: 'point_balance', type: 'INTEGER' },
    { name: 'created_at', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  message_templates: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'content', type: 'TEXT', notNull: true },
  ],
  message_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'customer_id', type: 'INTEGER' },
    { name: 'phone', type: 'TEXT', notNull: true },
    { name: 'message', type: 'TEXT', notNull: true },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  ad_templates: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'header', type: 'TEXT', notNull: true },
    { name: 'footer', type: 'TEXT', notNull: true },
    { name: 'opt_out', type: 'TEXT', notNull: true },
  ],
  products: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'price', type: 'TEXT' },
    { name: 'url', type: 'TEXT' },
    { name: 'description', type: 'TEXT' },
    { name: 'main_image_url', type: 'TEXT' },
    { name: 'detail_image_url', type: 'TEXT' },
    { name: 'available_methods', type: 'TEXT' },
    { name: 'category', type: 'TEXT' },
    { name: 'menu_category', type: 'TEXT' },
    { name: 'is_coupon_excludable', type: 'INTEGER' },
    { name: 'is_estimate_price', type: 'INTEGER', defaultValue: 0 },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_transactions: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'customer_name', type: 'TEXT', notNull: true },
    { name: 'customer_phone', type: 'TEXT', notNull: true },
    { name: 'product_name', type: 'TEXT', notNull: true },
    { name: 'amount', type: 'TEXT' },
    { name: 'order_date', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'order_id', type: 'TEXT' },
  ],
  crm_orders: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'customer_name', type: 'TEXT', notNull: true },
    { name: 'customer_phone', type: 'TEXT', notNull: true },
    { name: 'product_name', type: 'TEXT', notNull: true },
    { name: 'quantity', type: 'TEXT' },
    { name: 'total_price', type: 'TEXT' },
    { name: 'delivery_method', type: 'TEXT' },
    { name: 'shipping_address', type: 'TEXT' },
    { name: 'tracking_number', type: 'TEXT' },
    { name: 'attachment_url', type: 'TEXT' },
    { name: 'customer_memo', type: 'TEXT' },
    { name: 'order_date', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_payments: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'customer_name', type: 'TEXT', notNull: true },
    { name: 'payment_method', type: 'TEXT', notNull: true },
    { name: 'amount', type: 'TEXT', notNull: true },
    { name: 'payment_date', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'order_id', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_reservations: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'customer_name', type: 'TEXT', notNull: true },
    { name: 'customer_phone', type: 'TEXT', notNull: true },
    { name: 'service_name', type: 'TEXT', notNull: true },
    { name: 'reservation_date', type: 'TEXT' },
    { name: 'reservation_time', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_deliveries: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'customer_name', type: 'TEXT', notNull: true },
    { name: 'customer_phone', type: 'TEXT', notNull: true },
    { name: 'address', type: 'TEXT', notNull: true },
    { name: 'courier', type: 'TEXT' },
    { name: 'tracking_number', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'order_id', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  system_settings: [
    { name: 'id', type: 'TEXT', notNull: false },
    { name: 'key', type: 'TEXT', notNull: true },
    { name: 'value', type: 'TEXT', notNull: true },
  ],
  crm_operators: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'username', type: 'TEXT', notNull: true },
    { name: 'password_hash', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'role', type: 'TEXT', notNull: true },
    { name: 'employee_number', type: 'TEXT' },
    { name: 'phone', type: 'TEXT' },
    { name: 'my_card_image_url', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_instagram_posts: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'product_id', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'content', type: 'TEXT' },
    { name: 'image_url', type: 'TEXT' },
    { name: 'scheduled_at', type: 'TEXT' },
    { name: 'posted_at', type: 'TEXT' },
    { name: 'error_message', type: 'TEXT' },
    { name: 'likes_count', type: 'INTEGER' },
    { name: 'comments_count', type: 'INTEGER' },
  ],
  instagram_marketing_settings: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'is_autopilot', type: 'INTEGER', notNull: true },
    { name: 'autopilot_interval', type: 'TEXT' },
    { name: 'autopilot_time', type: 'TEXT' },
    { name: 'tone_style', type: 'TEXT' },
    { name: 'instagram_username', type: 'TEXT' },
    { name: 'access_token', type: 'TEXT' },
  ],
  crm_naver_blog_posts: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'product_id', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT' },
    { name: 'content', type: 'TEXT' },
    { name: 'target_keywords', type: 'TEXT' },
    { name: 'image_url', type: 'TEXT' },
    { name: 'sub_image_url', type: 'TEXT' },
    { name: 'scheduled_at', type: 'TEXT' },
    { name: 'posted_at', type: 'TEXT' },
    { name: 'error_message', type: 'TEXT' },
    { name: 'views_count', type: 'INTEGER' },
    { name: 'likes_count', type: 'INTEGER' },
  ],
  naver_blog_marketing_settings: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'is_autopilot', type: 'INTEGER', notNull: true },
    { name: 'autopilot_interval', type: 'TEXT' },
    { name: 'autopilot_time', type: 'TEXT' },
    { name: 'tone_style', type: 'TEXT' },
    { name: 'naver_blog_id', type: 'TEXT' },
    { name: 'api_client_id', type: 'TEXT' },
    { name: 'api_client_secret', type: 'TEXT' },
  ],
  coupons: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'code', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'discount_type', type: 'TEXT', notNull: true },
    { name: 'discount_value', type: 'INTEGER', notNull: true },
    { name: 'min_order_amount', type: 'INTEGER', notNull: true },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'expires_at', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_coupons_restrictions: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'coupon_id', type: 'TEXT', notNull: true },
    { name: 'restriction_type', type: 'TEXT', notNull: true },
    { name: 'target_type', type: 'TEXT', notNull: true },
    { name: 'target_value', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_point_history: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'customer_id', type: 'INTEGER', notNull: true },
    { name: 'transaction_type', type: 'TEXT', notNull: true },
    { name: 'amount', type: 'INTEGER', notNull: true },
    { name: 'balance_after', type: 'INTEGER', notNull: true },
    { name: 'description', type: 'TEXT' },
    { name: 'related_entity_type', type: 'TEXT' },
    { name: 'related_entity_id', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_estimates: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'type', type: 'TEXT', notNull: true },
    { name: 'direction_status', type: 'TEXT' },
    { name: 'partner_name', type: 'TEXT', notNull: true },
    { name: 'partner_phone', type: 'TEXT' },
    { name: 'partner_manager', type: 'TEXT' },
    { name: 'total_amount', type: 'INTEGER' },
    { name: 'file_url', type: 'TEXT' },
    { name: 'business_license_url', type: 'TEXT' },
    { name: 'ai_parsed', type: 'INTEGER', defaultValue: 0 },
    { name: 'tags', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'sales_order_number', type: 'TEXT' },
    { name: 'purchase_order_number', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_estimate_items: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'estimate_id', type: 'TEXT', notNull: true },
    { name: 'product_id', type: 'TEXT' },
    { name: 'item_code', type: 'TEXT' },
    { name: 'product_name', type: 'TEXT', notNull: true },
    { name: 'spec', type: 'TEXT' },
    { name: 'quantity', type: 'INTEGER', notNull: true },
    { name: 'unit_price', type: 'INTEGER', notNull: true },
    { name: 'amount', type: 'INTEGER', notNull: true },
    { name: 'delivery_date', type: 'TEXT' },
    { name: 'valid_item_code', type: 'TEXT' },
  ],
  crm_purchase_orders: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'estimate_id', type: 'TEXT' },
    { name: 'vendor_name', type: 'TEXT', notNull: true },
    { name: 'vendor_phone', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'total_amount', type: 'INTEGER' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'completed_at', type: 'TEXT' },
  ],
  crm_sales_orders: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'estimate_id', type: 'TEXT' },
    { name: 'client_order_no', type: 'TEXT' },
    { name: 'customer_name', type: 'TEXT', notNull: true },
    { name: 'customer_phone', type: 'TEXT' },
    { name: 'customer_manager', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'total_amount', type: 'INTEGER' },
    { name: 'delivery_date', type: 'TEXT' },
    { name: 'order_date', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_partners: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'type', type: 'TEXT', notNull: true },
    { name: 'company_name', type: 'TEXT', notNull: true },
    { name: 'business_number', type: 'TEXT' },
    { name: 'representative', type: 'TEXT' },
    { name: 'phone', type: 'TEXT' },
    { name: 'fax', type: 'TEXT' },
    { name: 'manager_name', type: 'TEXT' },
    { name: 'manager_phone', type: 'TEXT' },
    { name: 'manager_position', type: 'TEXT' },
    { name: 'manager_email', type: 'TEXT' },
    { name: 'email', type: 'TEXT' },
    { name: 'address', type: 'TEXT' },
    { name: 'vip_level', type: 'TEXT', defaultValue: 'NORMAL' },
    { name: 'credit_limit', type: 'INTEGER', defaultValue: 0 },
    { name: 'business_license_url', type: 'TEXT' },
    { name: 'memo', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_snaptasks: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'status', type: 'TEXT', defaultValue: 'ACTIVE' },
    { name: 'partner_id', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT', notNull: true },
  ],
  crm_snaptask_items: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'task_id', type: 'TEXT', notNull: true },
    { name: 'content_text', type: 'TEXT' },
    { name: 'file_url', type: 'TEXT' },
    { name: 'file_type', type: 'TEXT', notNull: true },
    { name: 'ai_analysis', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_snaptask_actions: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'task_id', type: 'TEXT', notNull: true },
    { name: 'action_type', type: 'TEXT', notNull: true },
    { name: 'description', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_partner_contacts: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'partner_id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'position', type: 'TEXT' },
    { name: 'phone', type: 'TEXT' },
    { name: 'email', type: 'TEXT' },
    { name: 'card_image_url', type: 'TEXT' },
    { name: 'is_primary', type: 'INTEGER', defaultValue: 0 },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  inventory_items: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'type', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'category', type: 'TEXT', notNull: true },
    { name: 'price', type: 'REAL', notNull: true },
    { name: 'partner', type: 'TEXT' },
    { name: 'stock', type: 'INTEGER', notNull: true },
    { name: 'safeStock', type: 'INTEGER', notNull: true },
    { name: 'location', type: 'TEXT' },
    { name: 'spec', type: 'TEXT' },
    { name: 'unitType', type: 'TEXT' },
    { name: 'unitValue', type: 'TEXT' },
    { name: 'boxContains', type: 'INTEGER' },
    { name: 'description', type: 'TEXT' },
    { name: 'tags', type: 'TEXT' },
    { name: 'barcode', type: 'TEXT' },
    { name: 'createdAt', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_inventory_inbounds: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'partner_name', type: 'TEXT' },
    { name: 'inbound_date', type: 'TEXT', notNull: true },
    { name: 'total_amount', type: 'INTEGER', defaultValue: 0 },
    { name: 'pdf_file_path', type: 'TEXT' },
    { name: 'file_hash', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT', notNull: true },
  ],
  crm_inventory_inbound_items: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'inbound_id', type: 'TEXT', notNull: true },
    { name: 'item_name', type: 'TEXT', notNull: true },
    { name: 'spec', type: 'TEXT' },
    { name: 'quantity', type: 'INTEGER', notNull: true },
    { name: 'price', type: 'INTEGER', defaultValue: 0 },
    { name: 'barcode', type: 'TEXT' },
    { name: 'matched_item_id', type: 'INTEGER' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  ai_token_usage_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'model', type: 'TEXT', notNull: true },
    { name: 'purpose', type: 'TEXT', notNull: true },
    { name: 'prompt_tokens', type: 'INTEGER', notNull: true },
    { name: 'completion_tokens', type: 'INTEGER', notNull: true },
    { name: 'total_tokens', type: 'INTEGER', notNull: true },
    { name: 'user_name', type: 'TEXT' },
    { name: 'menu_path', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  tracked_items: [
    { name: 'item_id', type: 'INTEGER', notNull: true },
    { name: 'item_code', type: 'TEXT', notNull: true },
    { name: 'item_name', type: 'TEXT', notNull: true },
    { name: 'category', type: 'TEXT', notNull: true },
    { name: 'spec', type: 'TEXT' },
    { name: 'base_price', type: 'REAL', notNull: true },
    { name: 'target_margin_rate', type: 'REAL', notNull: true },
    { name: 'created_at', type: 'TEXT' },
  ],
  target_urls: [
    { name: 'url_id', type: 'INTEGER', notNull: true },
    { name: 'item_id', type: 'INTEGER', notNull: true },
    { name: 'site_name', type: 'TEXT', notNull: true },
    { name: 'target_url', type: 'TEXT', notNull: true },
    { name: 'css_selector', type: 'TEXT', notNull: true },
    { name: 'xpath', type: 'TEXT' },
    { name: 'cron_interval', type: 'TEXT', notNull: true },
    { name: 'is_active', type: 'INTEGER', notNull: true },
    { name: 'created_at', type: 'TEXT' },
  ],
  price_histories: [
    { name: 'history_id', type: 'INTEGER', notNull: true },
    { name: 'url_id', type: 'INTEGER', notNull: true },
    { name: 'captured_price', type: 'REAL', notNull: true },
    { name: 'captured_at', type: 'TEXT', notNull: true },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'error_message', type: 'TEXT' },
  ],
  alert_rules: [
    { name: 'rule_id', type: 'INTEGER', notNull: true },
    { name: 'item_id', type: 'INTEGER', notNull: true },
    { name: 'rule_name', type: 'TEXT', notNull: true },
    { name: 'condition_type', type: 'TEXT', notNull: true },
    { name: 'threshold_value', type: 'REAL', notNull: true },
    { name: 'phone_number', type: 'TEXT', notNull: true },
    { name: 'sms_template', type: 'TEXT', notNull: true },
    { name: 'is_enabled', type: 'INTEGER', notNull: true },
  ],
  alert_logs: [
    { name: 'log_id', type: 'INTEGER', notNull: true },
    { name: 'rule_id', type: 'INTEGER', notNull: true },
    { name: 'sent_price', type: 'REAL', notNull: true },
    { name: 'sent_message', type: 'TEXT', notNull: true },
    { name: 'sent_at', type: 'TEXT', notNull: true },
    { name: 'api_response', type: 'TEXT' },
  ],
  inventory_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'itemId', type: 'INTEGER', notNull: true },
    { name: 'itemName', type: 'TEXT', notNull: true },
    { name: 'itemType', type: 'TEXT', notNull: true },
    { name: 'changeType', type: 'TEXT', notNull: true },
    { name: 'quantity', type: 'INTEGER', notNull: true },
    { name: 'price', type: 'REAL', notNull: true },
    { name: 'operator', type: 'TEXT', notNull: true },
    { name: 'note', type: 'TEXT' },
    { name: 'createdAt', type: 'TEXT', notNull: true },
  ],
  crm_expenses: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'category', type: 'TEXT', notNull: true },
    { name: 'amount', type: 'INTEGER', notNull: true },
    { name: 'expense_date', type: 'TEXT', notNull: true },
    { name: 'payment_method', type: 'TEXT', notNull: true },
    { name: 'attachment_url', type: 'TEXT' },
    { name: 'ai_analysis', type: 'TEXT' },
    { name: 'memo', type: 'TEXT' },
    { name: 'approval_status', type: 'TEXT', defaultValue: 'PENDING' },
    { name: 'approval_memo', type: 'TEXT' },
    { name: 'approved_at', type: 'TEXT' },
    { name: 'actual_expense_date', type: 'TEXT' },
    { name: 'deduction_amount', type: 'INTEGER', defaultValue: 0 },
    { name: 'transfer_fee', type: 'INTEGER', defaultValue: 0 },
    { name: 'card_approval_no', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  expense_settings: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'monthly_budget', type: 'INTEGER', notNull: true },
    { name: 'is_alert_enabled', type: 'INTEGER', notNull: true },
    { name: 'alert_threshold_percent', type: 'INTEGER', notNull: true },
    { name: 'alert_sms_template', type: 'TEXT', notNull: true },
    { name: 'alert_phone', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_governance_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'doc_type', type: 'TEXT', notNull: true },
    { name: 'doc_id', type: 'TEXT', notNull: true },
    { name: 'doc_title', type: 'TEXT', notNull: true },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'reason', type: 'TEXT', notNull: true },
    { name: 'operator', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  expense_categories: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'main_category', type: 'TEXT', notNull: true },
    { name: 'mid_category', type: 'TEXT', notNull: true },
    { name: 'sub_category', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  expense_tags: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'scope', type: 'TEXT', defaultValue: 'global' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  expense_departments: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  expense_employees: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  expense_projects: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  shared_dashboards: [
    { name: 'share_id', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'sql_query', type: 'TEXT', notNull: true },
    { name: 'table_name', type: 'TEXT' },
    { name: 'display_name', type: 'TEXT' },
    { name: 'chart_spec_json', type: 'TEXT' },
    { name: 'briefing_markdown', type: 'TEXT' },
    { name: 'refresh_interval', type: 'TEXT', defaultValue: 'NONE' },
    { name: 'last_refreshed_at', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'is_active', type: 'INTEGER', defaultValue: 1 },
    { name: 'sort_order', type: 'INTEGER', defaultValue: 0 },
    { name: 'is_pinned', type: 'INTEGER', defaultValue: 1 },
    { name: 'custom_title', type: 'TEXT' },
  ],
  system_menu_settings: [
    { name: 'menu_href', type: 'TEXT', notNull: true },
    { name: 'is_enabled', type: 'INTEGER', notNull: true, defaultValue: 1 },
    { name: 'sort_order', type: 'INTEGER', notNull: true },
  ],
  system_mail_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'sender', type: 'TEXT', notNull: true },
    { name: 'subject', type: 'TEXT', notNull: true },
    { name: 'received_at', type: 'TEXT', notNull: true },
    { name: 'ai_summary', type: 'TEXT', notNull: true },
    { name: 'intent', type: 'TEXT', notNull: true },
    { name: 'risk_level', type: 'TEXT', notNull: true },
    { name: 'action_type', type: 'TEXT' },
    { name: 'action_result', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_deadstock_proposals: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'item_id', type: 'INTEGER', notNull: true },
    { name: 'target_company', type: 'TEXT', notNull: true },
    { name: 'target_email', type: 'TEXT', notNull: true },
    { name: 'subject', type: 'TEXT', notNull: true },
    { name: 'content', type: 'TEXT', notNull: true },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'replied_content', type: 'TEXT' },
    { name: 'replied_at', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_meetings: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'date', type: 'TEXT', notNull: true },
    { name: 'attendees', type: 'TEXT' },
    { name: 'transcript', type: 'TEXT' },
    { name: 'summary', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'audio_url', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_meeting_tasks: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'meeting_id', type: 'INTEGER', notNull: true },
    { name: 'assignee_name', type: 'TEXT', notNull: true },
    { name: 'assignee_email', type: 'TEXT' },
    { name: 'task_desc', type: 'TEXT', notNull: true },
    { name: 'due_date', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  ai_contextual_help: [
    { name: 'hint_key', type: 'TEXT', notNull: true },
    { name: 'hint_text', type: 'TEXT', notNull: true },
    { name: 'ai_explanation', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  form_templates: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'template_name', type: 'TEXT', notNull: true },
    { name: 'document_type', type: 'TEXT', notNull: true },
    { name: 'file_path', type: 'TEXT', notNull: true },
    { name: 'orientation', type: 'TEXT', notNull: true },
    { name: 'is_active', type: 'INTEGER', notNull: true },
    { name: 'query_sql', type: 'TEXT' },
    { name: 'query_params', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  form_mappings: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'template_id', type: 'INTEGER', notNull: true },
    { name: 'field_key', type: 'TEXT', notNull: true },
    { name: 'field_label', type: 'TEXT', notNull: true },
    { name: 'pos_x', type: 'REAL', notNull: true },
    { name: 'pos_y', type: 'REAL', notNull: true },
    { name: 'font_size', type: 'INTEGER' },
    { name: 'font_weight', type: 'TEXT' },
    { name: 'text_align', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_employment_certificate_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'staff_id', type: 'INTEGER', notNull: true },
    { name: 'staff_name', type: 'TEXT', notNull: true },
    { name: 'joined_date', type: 'TEXT' },
    { name: 'degree_level', type: 'TEXT' },
    { name: 'major_name', type: 'TEXT' },
    { name: 'address', type: 'TEXT' },
    { name: 'usage', type: 'TEXT' },
    { name: 'issue_date', type: 'TEXT' },
    { name: 'issue_dept', type: 'TEXT' },
    { name: 'issue_by', type: 'TEXT' },
    { name: 'extra_data', type: 'TEXT' },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_web_templates: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'template_name', type: 'TEXT', notNull: true },
    { name: 'html_content', type: 'TEXT', notNull: true },
    { name: 'web_html_content', type: 'TEXT' },
    { name: 'document_type', type: 'TEXT' },
    { name: 'is_active', type: 'INTEGER', defaultValue: 1 },
    { name: 'is_print_active', type: 'INTEGER', defaultValue: 1 },
    { name: 'is_web_active', type: 'INTEGER', defaultValue: 1 },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_web_form_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'template_id', type: 'INTEGER', notNull: true },
    { name: 'record_id', type: 'TEXT', notNull: true },
    { name: 'record_name', type: 'TEXT' },
    { name: 'print_data', type: 'TEXT', notNull: true },
    { name: 'issue_date', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_web_published_sites: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'domain_type', type: 'TEXT', notNull: true },
    { name: 'domain_url', type: 'TEXT', notNull: true },
    { name: 'html_content', type: 'TEXT', notNull: true },
    { name: 'config_json', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT' },
    { name: 'description', type: 'TEXT' },
    { name: 'is_active', type: 'INTEGER', defaultValue: 1 },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  easybot_action_audit_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'operator_username', type: 'TEXT' },
    { name: 'original_prompt', type: 'TEXT' },
    { name: 'action_name', type: 'TEXT' },
    { name: 'arguments_json', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'execution_result', type: 'TEXT' },
    { name: 'error_message', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_partner_ai_reports: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'partner_id', type: 'TEXT', notNull: true },
    { name: 'company_name', type: 'TEXT', notNull: true },
    { name: 'report_type', type: 'TEXT', notNull: true },
    { name: 'risk_grade', type: 'TEXT' },
    { name: 'summary', type: 'TEXT' },
    { name: 'result_json', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  safety_policies: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'year', type: 'TEXT', notNull: true },
    { name: 'policy_title', type: 'TEXT', notNull: true },
    { name: 'targets_json', type: 'TEXT', notNull: true },
    { name: 'established_at', type: 'TEXT', notNull: true },
    { name: 'established_by', type: 'TEXT', notNull: true },
  ],
  safety_risk_assessments: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'work_name', type: 'TEXT', notNull: true },
    { name: 'work_date', type: 'TEXT', notNull: true },
    { name: 'hazards_json', type: 'TEXT', notNull: true },
    { name: 'risk_level', type: 'TEXT', notNull: true },
    { name: 'evaluated_by', type: 'TEXT', notNull: true },
    { name: 'approved_at', type: 'TEXT' },
    { name: 'status', type: 'TEXT', defaultValue: 'DRAFT' },
  ],
  safety_tbm_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'tbm_date', type: 'TEXT', notNull: true },
    { name: 'work_leader', type: 'TEXT', notNull: true },
    { name: 'weather_info', type: 'TEXT' },
    { name: 'tbm_script', type: 'TEXT', notNull: true },
    { name: 'attendees_count', type: 'INTEGER', defaultValue: 0 },
    { name: 'attendee_signatures', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  safety_near_misses: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'reporter_name', type: 'TEXT', notNull: true },
    { name: 'hazard_location', type: 'TEXT', notNull: true },
    { name: 'description', type: 'TEXT', notNull: true },
    { name: 'photo_url', type: 'TEXT' },
    { name: 'risk_grade', type: 'TEXT', notNull: true },
    { name: 'action_status', type: 'TEXT', defaultValue: 'PENDING' },
    { name: 'action_description', type: 'TEXT' },
    { name: 'action_photo_url', type: 'TEXT' },
    { name: 'action_completed_at', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  safety_inspect_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'inspect_title', type: 'TEXT', notNull: true },
    { name: 'inspect_date', type: 'TEXT', notNull: true },
    { name: 'inspector_name', type: 'TEXT', notNull: true },
    { name: 'checklist_json', type: 'TEXT', notNull: true },
    { name: 'fail_actions_json', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_financial_statements: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'company_id', type: 'TEXT', notNull: true },
    { name: 'company_type', type: 'TEXT', notNull: true },
    { name: 'fiscal_year', type: 'INTEGER', notNull: true },
    { name: 'fiscal_quarter', type: 'TEXT', notNull: true, defaultValue: 'YR' },
    { name: 'total_assets', type: 'INTEGER', defaultValue: 0 },
    { name: 'total_liabilities', type: 'INTEGER', defaultValue: 0 },
    { name: 'total_equity', type: 'INTEGER', defaultValue: 0 },
    { name: 'revenue', type: 'INTEGER', defaultValue: 0 },
    { name: 'operating_income', type: 'INTEGER', defaultValue: 0 },
    { name: 'net_income', type: 'INTEGER', defaultValue: 0 },
    { name: 'pdf_file_path', type: 'TEXT' },
    { name: 'parsed_raw_json', type: 'TEXT' },
  ],
  crm_financial_statement_items: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'statement_id', type: 'TEXT', notNull: true },
    { name: 'category', type: 'TEXT', notNull: true },
    { name: 'account_name', type: 'TEXT', notNull: true },
    { name: 'amount', type: 'REAL', defaultValue: 0 },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT', notNull: true },
  ],
  crm_financial_analysis_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'statement_id', type: 'TEXT', notNull: true },
    { name: 'z_score', type: 'REAL', defaultValue: 0 },
    { name: 'risk_grade', type: 'TEXT', notNull: true },
    { name: 'forecast_text', type: 'TEXT' },
    { name: 'consulting_text', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT', notNull: true },
  ],
  crm_recruitment_applicants: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'age', type: 'TEXT' },
    { name: 'phone', type: 'TEXT' },
    { name: 'experience', type: 'TEXT' },
    { name: 'motivation', type: 'TEXT' },
    { name: 'matching_score', type: 'INTEGER', defaultValue: 0 },
    { name: 'status', type: 'TEXT', defaultValue: 'applied' },
    { name: 'signature_url', type: 'TEXT' },
    { name: 'signed_at', type: 'TEXT' },
    { name: 'resume_file_path', type: 'TEXT' },
    { name: 'tech_stacks', type: 'TEXT' },
    { name: 'interview_logs', type: 'TEXT' },
    { name: 'ai_evaluation', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_grant_announcements: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'agency', type: 'TEXT', notNull: true },
    { name: 'match_score', type: 'INTEGER' },
    { name: 'match_guide', type: 'TEXT' },
    { name: 'budget', type: 'INTEGER' },
    { name: 'end_date', type: 'TEXT', notNull: true },
  ],
  crm_grant_bookmarks: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'announcement_id', type: 'TEXT', notNull: true },
  ],
  crm_grant_rnd_plans: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'announcement_id', type: 'TEXT', notNull: true },
    { name: 'plan_data', type: 'TEXT', notNull: true },
  ],
  crm_grant_company_profile: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'establishmentYear', type: 'INTEGER' },
    { name: 'employeeCount', type: 'INTEGER' },
    { name: 'patentsCount', type: 'INTEGER' },
    { name: 'femaleEmployeeRatio', type: 'INTEGER' },
    { name: 'youthEmployeeRatio', type: 'INTEGER' },
    { name: 'sector', type: 'TEXT' },
  ],
  crm_quality_checklist_submissions: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'lotNo', type: 'TEXT', notNull: true },
    { name: 'inspector', type: 'TEXT', notNull: true },
    { name: 'checkItems', type: 'TEXT', notNull: true },
    { name: 'signatureData', type: 'TEXT' },
    { name: 'photoUrl', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'submittedAt', type: 'TEXT', notNull: true },
  ],
  crm_quality_ncr_items: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'date', type: 'TEXT', notNull: true },
    { name: 'itemName', type: 'TEXT', notNull: true },
    { name: 'defectCode', type: 'TEXT' },
    { name: 'defectType', type: 'TEXT' },
    { name: 'quantity', type: 'INTEGER' },
    { name: 'reporter', type: 'TEXT' },
    { name: 'status', type: 'TEXT', notNull: true },
    { name: 'description', type: 'TEXT' },
    { name: 'actionPlan', type: 'TEXT' },
  ],
  crm_quality_ncr_similar_cases: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'similarity', type: 'REAL' },
    { name: 'rootCause', type: 'TEXT' },
    { name: 'actionTaken', type: 'TEXT' },
  ],
  crm_quality_sensors_status: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'equipmentName', type: 'TEXT', notNull: true },
    { name: 'operationalStatus', type: 'TEXT' },
    { name: 'vibrationRms', type: 'REAL' },
    { name: 'motorCurrent', type: 'REAL' },
    { name: 'bearingTemp', type: 'REAL' },
    { name: 'anomalyScore', type: 'INTEGER' },
    { name: 'threshold', type: 'INTEGER' },
  ],
  crm_quality_sensors_contribution: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'rate', type: 'INTEGER' },
  ],
  crm_quality_sensors_timeline: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'time', type: 'TEXT' },
    { name: 'vibration', type: 'REAL' },
    { name: 'current', type: 'REAL' },
    { name: 'temperature', type: 'REAL' },
    { name: 'anomalyScore', type: 'INTEGER' },
  ],
  crm_quality_spc_config: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'targetValue', type: 'REAL' },
    { name: 'ucl', type: 'REAL' },
    { name: 'lcl', type: 'REAL' },
    { name: 'usl', type: 'REAL' },
    { name: 'lsl', type: 'REAL' },
    { name: 'currentCpk', type: 'REAL' },
    { name: 'cpkStatus', type: 'TEXT' },
    { name: 'futureRiskProbability', type: 'INTEGER' },
  ],
  crm_quality_spc_samples: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'batch', type: 'TEXT', notNull: true },
    { name: 'value', type: 'REAL' },
    { name: 'cpk', type: 'REAL' },
    { name: 'timestamp', type: 'TEXT' },
  ],
  crm_quality_spc_predictions: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'batch', type: 'TEXT', notNull: true },
    { name: 'value', type: 'REAL' },
    { name: 'cpk', type: 'REAL' },
    { name: 'timestamp', type: 'TEXT' },
    { name: 'risk', type: 'INTEGER' },
  ],
  crm_quality_spc_features: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'value', type: 'INTEGER' },
    { name: 'color', type: 'TEXT' },
  ],
  crm_quality_vision_model: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'activeModel', type: 'TEXT' },
    { name: 'goldenSamplesCount', type: 'INTEGER' },
    { name: 'lastTrainedAt', type: 'TEXT' },
    { name: 'anomalyThreshold', type: 'REAL' },
  ],
  crm_quality_vision_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'timestamp', type: 'TEXT' },
    { name: 'itemName', type: 'TEXT' },
    { name: 'anomalyScore', type: 'REAL' },
    { name: 'status', type: 'TEXT' },
    { name: 'defectType', type: 'TEXT' },
    { name: 'imageUrl', type: 'TEXT' },
    { name: 'isReviewed', type: 'INTEGER' },
  ],
  crm_facilities: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'name', type: 'TEXT', notNull: true },
    { name: 'manufacturer', type: 'TEXT' },
    { name: 'model_name', type: 'TEXT' },
    { name: 'serial_number', type: 'TEXT' },
    { name: 'manufacture_year', type: 'INTEGER' },
    { name: 'specifications', type: 'TEXT' },
    { name: 'location', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'health_score', type: 'REAL' },
    { name: 'vibration_rms', type: 'REAL' },
    { name: 'created_at', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
  ],
  crm_facility_checklists: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'equipmentId', type: 'TEXT', notNull: true },
    { name: 'inspector', type: 'TEXT', notNull: true },
    { name: 'checks', type: 'TEXT' },
    { name: 'signatureData', type: 'TEXT' },
    { name: 'audioUrl', type: 'TEXT' },
    { name: 'status', type: 'TEXT' },
    { name: 'checkedAt', type: 'TEXT' },
  ],
  crm_facility_repair_logs: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'date', type: 'TEXT', notNull: true },
    { name: 'equipmentId', type: 'TEXT', notNull: true },
    { name: 'equipmentName', type: 'TEXT' },
    { name: 'errorCode', type: 'TEXT' },
    { name: 'symptom', type: 'TEXT' },
    { name: 'repairDesc', type: 'TEXT' },
    { name: 'mechanic', type: 'TEXT' },
    { name: 'cost', type: 'INTEGER' },
  ],
  crm_facility_repair_solutions: [
    { name: 'errorCode', type: 'TEXT', notNull: true },
    { name: 'rootCause', type: 'TEXT' },
    { name: 'actions', type: 'TEXT' },
    { name: 'similarHistory', type: 'TEXT' },
    { name: 'warehouse', type: 'TEXT' },
  ],
  crm_facility_predictive_summary: [
    { name: 'equipmentId', type: 'TEXT', notNull: true },
    { name: 'equipmentName', type: 'TEXT' },
    { name: 'healthScore', type: 'REAL' },
    { name: 'vibrationRms', type: 'REAL' },
  ],
  crm_facility_predictive_vibration: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'equipmentId', type: 'TEXT', notNull: true },
    { name: 'time', type: 'TEXT', notNull: true },
    { name: 'value', type: 'REAL', notNull: true },
  ],
  crm_facility_predictive_fft: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'equipmentId', type: 'TEXT', notNull: true },
    { name: 'frequency', type: 'REAL', notNull: true },
    { name: 'amplitude', type: 'REAL', notNull: true },
    { name: 'label', type: 'TEXT' },
  ],
  crm_facility_predictive_part_rul: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'equipmentId', type: 'TEXT', notNull: true },
    { name: 'partName', type: 'TEXT', notNull: true },
    { name: 'rulDays', type: 'INTEGER', notNull: true },
    { name: 'status', type: 'TEXT' },
    { name: 'percent', type: 'INTEGER' },
  ],
  rnd_centers: [
    { name: 'center_id', type: 'INTEGER', notNull: true },
    { name: 'company_id', type: 'INTEGER', notNull: true },
    { name: 'center_name', type: 'TEXT', notNull: true },
    { name: 'center_type', type: 'TEXT', notNull: true },
    { name: 'established_date', type: 'TEXT', notNull: true },
    { name: 'koita_reg_number', type: 'TEXT' },
    { name: 'postal_code', type: 'TEXT', notNull: true },
    { name: 'address_road', type: 'TEXT', notNull: true },
    { name: 'address_detail', type: 'TEXT' },
    { name: 'total_area_sqm', type: 'REAL', notNull: true },
    { name: 'is_active', type: 'INTEGER', defaultValue: 1 },
  ],
  rnd_staffs: [
    { name: 'staff_id', type: 'INTEGER', notNull: true },
    { name: 'center_id', type: 'INTEGER', notNull: true },
    { name: 'user_id', type: 'INTEGER', notNull: true },
    { name: 'staff_role', type: 'TEXT', notNull: true },
    { name: 'employment_status', type: 'TEXT', defaultValue: 'ACTIVE' },
    { name: 'degree_level', type: 'TEXT', notNull: true },
    { name: 'major_name', type: 'TEXT', notNull: true },
    { name: 'major_category', type: 'TEXT', notNull: true },
    { name: 'graduation_cert_ocr_json', type: 'TEXT' },
    { name: 'qualification_status', type: 'TEXT', defaultValue: 'PENDING' },
    { name: 'joined_date', type: 'TEXT', notNull: true },
    { name: 'resigned_date', type: 'TEXT' },
  ],
  rnd_spaces: [
    { name: 'space_check_id', type: 'INTEGER', notNull: true },
    { name: 'center_id', type: 'INTEGER', notNull: true },
    { name: 'check_date', type: 'TEXT', notNull: true },
    { name: 'image_url_entrance', type: 'TEXT', notNull: true },
    { name: 'image_url_layout', type: 'TEXT', notNull: true },
    { name: 'ai_analysis_result', type: 'TEXT' },
    { name: 'signage_status', type: 'TEXT', defaultValue: 'FAIL' },
    { name: 'partition_status', type: 'TEXT', defaultValue: 'PASS' },
    { name: 'overall_status', type: 'TEXT', defaultValue: '보완필요' },
    { name: 'inspector_notes', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT' },
  ],
  rnd_logs: [
    { name: 'log_id', type: 'INTEGER', notNull: true },
    { name: 'center_id', type: 'INTEGER', notNull: true },
    { name: 'author_id', type: 'INTEGER', notNull: true },
    { name: 'work_date', type: 'TEXT', notNull: true },
    { name: 'raw_source', type: 'TEXT', notNull: true },
    { name: 'raw_content', type: 'TEXT' },
    { name: 'audio_file_url', type: 'TEXT' },
    { name: 'ai_generated_title', type: 'TEXT' },
    { name: 'ai_generated_content', type: 'TEXT' },
    { name: 'approval_status', type: 'TEXT', defaultValue: 'DRAFT' },
    { name: 'approver_id', type: 'INTEGER' },
    { name: 'approved_at', type: 'TEXT' },
    { name: 'blockchain_hash', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
  ],
  rnd_compliance_alarms: [
    { name: 'alarm_id', type: 'INTEGER', notNull: true },
    { name: 'center_id', type: 'INTEGER', notNull: true },
    { name: 'category', type: 'TEXT', notNull: true },
    { name: 'severity', type: 'TEXT', defaultValue: 'INFO' },
    { name: 'message', type: 'TEXT', notNull: true },
    { name: 'due_date', type: 'TEXT' },
    { name: 'is_resolved', type: 'INTEGER', defaultValue: 0 },
    { name: 'resolved_at', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT' },
  ],
  crm_credential_vault: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'category', type: 'TEXT', notNull: true },
    { name: 'asset_name', type: 'TEXT', notNull: true },
    { name: 'login_id', type: 'TEXT' },
    { name: 'encrypted_password', type: 'TEXT', notNull: true },
    { name: 'iv', type: 'TEXT', notNull: true },
    { name: 'auth_tag', type: 'TEXT', notNull: true },
    { name: 'remarks', type: 'TEXT' },
    { name: 'owner_operator_id', type: 'INTEGER' },
    { name: 'status', type: 'TEXT', notNull: true, defaultValue: 'ACTIVE' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_credential_emergency_requests: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'credential_id', type: 'INTEGER', notNull: true },
    { name: 'requester_id', type: 'INTEGER', notNull: true },
    { name: 'request_reason', type: 'TEXT', notNull: true },
    { name: 'status', type: 'TEXT', notNull: true, defaultValue: 'PENDING' },
    { name: 'approved_by', type: 'TEXT' },
    { name: 'approved_at', type: 'TEXT' },
    { name: 'expires_at', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_credential_audit_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'credential_id', type: 'INTEGER' },
    { name: 'operator_id', type: 'INTEGER' },
    { name: 'operator_name', type: 'TEXT' },
    { name: 'action_type', type: 'TEXT', notNull: true },
    { name: 'access_reason', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  easybot_rules: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'title', type: 'TEXT', notNull: true },
    { name: 'target_table', type: 'TEXT', notNull: true },
    { name: 'conditions_sql', type: 'TEXT', notNull: true },
    { name: 'assignee_id', type: 'TEXT', notNull: true },
    { name: 'task_priority', type: 'TEXT', notNull: true, defaultValue: 'medium' },
    { name: 'task_title_template', type: 'TEXT', notNull: true },
    { name: 'task_content_template', type: 'TEXT', notNull: true },
    { name: 'is_active', type: 'INTEGER', notNull: true, defaultValue: 1 },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  easybot_rules_history: [
    { name: 'id', type: 'TEXT', notNull: true },
    { name: 'rule_id', type: 'TEXT', notNull: true },
    { name: 'action_type', type: 'TEXT', notNull: true },
    { name: 'previous_value_json', type: 'TEXT' },
    { name: 'new_value_json', type: 'TEXT' },
    { name: 'change_reason', type: 'TEXT' },
    { name: 'operator_id', type: 'TEXT', notNull: true },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_interpretation_sessions: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'user_id', type: 'TEXT', notNull: true },
    { name: 'source_lang', type: 'TEXT', notNull: true },
    { name: 'target_lang', type: 'TEXT', notNull: true },
    { name: 'tone_manner', type: 'TEXT', notNull: true },
    { name: 'file_path', type: 'TEXT' },
    { name: 'audio_file_path', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_interpretation_logs: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'uuid', type: 'TEXT' },
    { name: 'session_uuid', type: 'TEXT', notNull: true },
    { name: 'speaker_role', type: 'TEXT', notNull: true },
    { name: 'original_text', type: 'TEXT', notNull: true },
    { name: 'translated_text', type: 'TEXT', notNull: true },
    { name: 'audio_url', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
    { name: 'updated_at', type: 'TEXT' },
    { name: 'updated_by', type: 'TEXT' },
    { name: 'deleted_at', type: 'TEXT' },
    { name: 'deleted_by', type: 'TEXT' },
    { name: 'restored_at', type: 'TEXT' },
    { name: 'restored_by', type: 'TEXT' },
  ],
  crm_excel_signatures: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'header_signature', type: 'TEXT', notNull: true },
    { name: 'partner_name', type: 'TEXT' },
    { name: 'transaction_type', type: 'TEXT' },
    { name: 'is_auto_approve', type: 'INTEGER', defaultValue: 1 },
    { name: 'mapping_info', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  crm_inbound_excel_signatures: [
    { name: 'id', type: 'INTEGER', notNull: true },
    { name: 'header_signature', type: 'TEXT', notNull: true },
    { name: 'partner_name', type: 'TEXT' },
    { name: 'is_auto_approve', type: 'INTEGER', defaultValue: 1 },
    { name: 'mapping_info', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  import_master: [
    { name: 'so_number', type: 'TEXT', notNull: true },
    { name: 'po_number', type: 'TEXT', notNull: true },
    { name: 'invoice_number', type: 'TEXT' },
    { name: 'order_date', type: 'TEXT', notNull: true },
    { name: 'ship_date', type: 'TEXT' },
    { name: 'invoice_date', type: 'TEXT', notNull: true },
    { name: 'air_waybill_nbr', type: 'TEXT' },
    { name: 'ship_via', type: 'TEXT' },
    { name: 'terms_of_sale', type: 'TEXT' },
    { name: 'payment_terms', type: 'TEXT' },
    { name: 'exporter_name', type: 'TEXT' },
    { name: 'tags', type: 'TEXT' },
    { name: 'file_path', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  import_items: [
    { name: 'item_id', type: 'INTEGER', notNull: true },
    { name: 'so_number', type: 'TEXT', notNull: true },
    { name: 'part_number', type: 'TEXT', notNull: true },
    { name: 'description', type: 'TEXT' },
    { name: 'quantity', type: 'REAL', notNull: true },
    { name: 'unit_price', type: 'REAL', notNull: true },
    { name: 'amount', type: 'REAL', notNull: true },
    { name: 'currency', type: 'TEXT', defaultValue: 'USD' },
    { name: 'hs_code', type: 'TEXT' },
    { name: 'country_of_origin', type: 'TEXT', defaultValue: 'US' },
    { name: 'lot_number', type: 'TEXT' },
    { name: 'mfg_date', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
  import_finance: [
    { name: 'finance_id', type: 'INTEGER', notNull: true },
    { name: 'so_number', type: 'TEXT', notNull: true },
    { name: 'total_invoice_value', type: 'REAL', notNull: true },
    { name: 'payment_due_date', type: 'TEXT', notNull: true },
    { name: 'is_paid', type: 'INTEGER', defaultValue: 0 },
    { name: 'paid_date', type: 'TEXT' },
    { name: 'bank_name', type: 'TEXT' },
    { name: 'account_number', type: 'TEXT' },
    { name: 'swift_code', type: 'TEXT' },
    { name: 'created_at', type: 'TEXT', notNull: true },
  ],
} as const;

export const TABLES = {
  crm_customers: {
    name: 'crm_customers',
    displayName: '고객 명단',
    columns: COLUMN_DEFINITIONS.crm_customers.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_customers.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  message_templates: {
    name: 'message_templates',
    displayName: '문자 템플릿',
    columns: COLUMN_DEFINITIONS.message_templates.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.message_templates.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  message_logs: {
    name: 'message_logs',
    displayName: '발송 내역',
    columns: COLUMN_DEFINITIONS.message_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.message_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  ad_templates: {
    name: 'ad_templates',
    displayName: '광고 템플릿',
    columns: COLUMN_DEFINITIONS.ad_templates.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.ad_templates.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  products: {
    name: 'products',
    displayName: '광고 상품',
    columns: COLUMN_DEFINITIONS.products.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.products.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
    duplicateAction: 'update',
  },
  crm_transactions: {
    name: 'crm_transactions',
    displayName: '거래 내역',
    columns: COLUMN_DEFINITIONS.crm_transactions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_transactions.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_orders: {
    name: 'crm_orders',
    displayName: '주문 내역',
    columns: COLUMN_DEFINITIONS.crm_orders.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_orders.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
    duplicateAction: 'update',
  },
  crm_payments: {
    name: 'crm_payments',
    displayName: '결제 내역',
    columns: COLUMN_DEFINITIONS.crm_payments.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_payments.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_reservations: {
    name: 'crm_reservations',
    displayName: '예약 내역',
    columns: COLUMN_DEFINITIONS.crm_reservations.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_reservations.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_deliveries: {
    name: 'crm_deliveries',
    displayName: '배송 내역',
    columns: COLUMN_DEFINITIONS.crm_deliveries.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_deliveries.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  system_settings: {
    name: 'system_settings',
    displayName: '시스템 설정',
    columns: COLUMN_DEFINITIONS.system_settings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.system_settings.length,
    rowCount: 0,
    uniqueKeyColumns: ["key"],
  },
  crm_operators: {
    name: 'crm_operators',
    displayName: '운영자 권한 관리',
    columns: COLUMN_DEFINITIONS.crm_operators.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_operators.length,
    rowCount: 0,
    uniqueKeyColumns: ["username"],
  },
  crm_instagram_posts: {
    name: 'crm_instagram_posts',
    displayName: '인스타그램 포스팅 이력 및 예약',
    columns: COLUMN_DEFINITIONS.crm_instagram_posts.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_instagram_posts.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  instagram_marketing_settings: {
    name: 'instagram_marketing_settings',
    displayName: '인스타그램 마케팅 설정',
    columns: COLUMN_DEFINITIONS.instagram_marketing_settings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.instagram_marketing_settings.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_naver_blog_posts: {
    name: 'crm_naver_blog_posts',
    displayName: '네이버 블로그 포스팅 이력 및 예약',
    columns: COLUMN_DEFINITIONS.crm_naver_blog_posts.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_naver_blog_posts.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  naver_blog_marketing_settings: {
    name: 'naver_blog_marketing_settings',
    displayName: '네이버 블로그 마케팅 설정',
    columns: COLUMN_DEFINITIONS.naver_blog_marketing_settings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.naver_blog_marketing_settings.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  coupons: {
    name: 'coupons',
    displayName: '쿠폰 관리',
    columns: COLUMN_DEFINITIONS.coupons.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.coupons.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_coupons_restrictions: {
    name: 'crm_coupons_restrictions',
    displayName: '쿠폰 제한 관리',
    columns: COLUMN_DEFINITIONS.crm_coupons_restrictions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_coupons_restrictions.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_point_history: {
    name: 'crm_point_history',
    displayName: '적립금 내역',
    columns: COLUMN_DEFINITIONS.crm_point_history.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_point_history.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_estimates: {
    name: 'crm_estimates',
    displayName: '견적서 관리',
    columns: COLUMN_DEFINITIONS.crm_estimates.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_estimates.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_estimate_items: {
    name: 'crm_estimate_items',
    displayName: '견적서 품목 상세',
    columns: COLUMN_DEFINITIONS.crm_estimate_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_estimate_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_purchase_orders: {
    name: 'crm_purchase_orders',
    displayName: '발주서 관리',
    columns: COLUMN_DEFINITIONS.crm_purchase_orders.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_purchase_orders.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_sales_orders: {
    name: 'crm_sales_orders',
    displayName: '수주서 관리',
    columns: COLUMN_DEFINITIONS.crm_sales_orders.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_sales_orders.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_partners: {
    name: 'crm_partners',
    displayName: '거래처 관리',
    columns: COLUMN_DEFINITIONS.crm_partners.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_partners.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_snaptasks: {
    name: 'crm_snaptasks',
    displayName: '스냅태스크 관리',
    columns: COLUMN_DEFINITIONS.crm_snaptasks.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_snaptasks.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_snaptask_items: {
    name: 'crm_snaptask_items',
    displayName: '스냅태스크 상세 내역',
    columns: COLUMN_DEFINITIONS.crm_snaptask_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_snaptask_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_snaptask_actions: {
    name: 'crm_snaptask_actions',
    displayName: '스냅태스크 AI 액션 감사록',
    columns: COLUMN_DEFINITIONS.crm_snaptask_actions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_snaptask_actions.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_partner_contacts: {
    name: 'crm_partner_contacts',
    displayName: '거래처 담당자 명함첩',
    columns: COLUMN_DEFINITIONS.crm_partner_contacts.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_partner_contacts.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  inventory_items: {
    name: 'inventory_items',
    displayName: '재고 품목',
    columns: COLUMN_DEFINITIONS.inventory_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.inventory_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_inventory_inbounds: {
    name: 'crm_inventory_inbounds',
    displayName: '자율 입고 대장',
    columns: COLUMN_DEFINITIONS.crm_inventory_inbounds.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_inventory_inbounds.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_inventory_inbound_items: {
    name: 'crm_inventory_inbound_items',
    displayName: '자율 입고 상세 품목',
    columns: COLUMN_DEFINITIONS.crm_inventory_inbound_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_inventory_inbound_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  ai_token_usage_logs: {
    name: 'ai_token_usage_logs',
    displayName: 'AI 토큰 사용량 로그',
    columns: COLUMN_DEFINITIONS.ai_token_usage_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.ai_token_usage_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  tracked_items: {
    name: 'tracked_items',
    displayName: '가격 추적 품목',
    columns: COLUMN_DEFINITIONS.tracked_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.tracked_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["item_id"],
  },
  target_urls: {
    name: 'target_urls',
    displayName: '가격 감시 URL',
    columns: COLUMN_DEFINITIONS.target_urls.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.target_urls.length,
    rowCount: 0,
    uniqueKeyColumns: ["url_id"],
  },
  price_histories: {
    name: 'price_histories',
    displayName: '수집 가격 이력',
    columns: COLUMN_DEFINITIONS.price_histories.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.price_histories.length,
    rowCount: 0,
    uniqueKeyColumns: ["history_id"],
  },
  alert_rules: {
    name: 'alert_rules',
    displayName: '가격 알림 규칙',
    columns: COLUMN_DEFINITIONS.alert_rules.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.alert_rules.length,
    rowCount: 0,
    uniqueKeyColumns: ["rule_id"],
  },
  alert_logs: {
    name: 'alert_logs',
    displayName: '가격 알림 발송 로그',
    columns: COLUMN_DEFINITIONS.alert_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.alert_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["log_id"],
  },
  inventory_logs: {
    name: 'inventory_logs',
    displayName: '재고 변동 이력',
    columns: COLUMN_DEFINITIONS.inventory_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.inventory_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_expenses: {
    name: 'crm_expenses',
    displayName: '지출 내역',
    columns: COLUMN_DEFINITIONS.crm_expenses.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_expenses.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  expense_settings: {
    name: 'expense_settings',
    displayName: '지출 예산 설정',
    columns: COLUMN_DEFINITIONS.expense_settings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.expense_settings.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_governance_logs: {
    name: 'crm_governance_logs',
    displayName: 'AI 결재 및 데이터 거버넌스 감사록',
    columns: COLUMN_DEFINITIONS.crm_governance_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_governance_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  expense_categories: {
    name: 'expense_categories',
    displayName: '지출 계정과목 관리',
    columns: COLUMN_DEFINITIONS.expense_categories.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.expense_categories.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  expense_tags: {
    name: 'expense_tags',
    displayName: '통합 공통 태그 관리',
    columns: COLUMN_DEFINITIONS.expense_tags.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.expense_tags.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  expense_departments: {
    name: 'expense_departments',
    displayName: '지출 부서 관리',
    columns: COLUMN_DEFINITIONS.expense_departments.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.expense_departments.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  expense_employees: {
    name: 'expense_employees',
    displayName: '지출 임직원 관리',
    columns: COLUMN_DEFINITIONS.expense_employees.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.expense_employees.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  expense_projects: {
    name: 'expense_projects',
    displayName: '지출 프로젝트 관리',
    columns: COLUMN_DEFINITIONS.expense_projects.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.expense_projects.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  shared_dashboards: {
    name: 'shared_dashboards',
    displayName: '공유 대시보드 관리',
    columns: COLUMN_DEFINITIONS.shared_dashboards.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.shared_dashboards.length,
    rowCount: 0,
    uniqueKeyColumns: ["share_id"],
  },
  system_menu_settings: {
    name: 'system_menu_settings',
    displayName: '시스템 메뉴 설정',
    columns: COLUMN_DEFINITIONS.system_menu_settings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.system_menu_settings.length,
    rowCount: 0,
    uniqueKeyColumns: ["menu_href"],
    duplicateAction: 'update',
  },
  system_mail_logs: {
    name: 'system_mail_logs',
    displayName: '메일 AI 관제 로그',
    columns: COLUMN_DEFINITIONS.system_mail_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.system_mail_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_deadstock_proposals: {
    name: 'crm_deadstock_proposals',
    displayName: '불용자재 제안 메일 로그',
    columns: COLUMN_DEFINITIONS.crm_deadstock_proposals.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_deadstock_proposals.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_meetings: {
    name: 'crm_meetings',
    displayName: '회의 대장',
    columns: COLUMN_DEFINITIONS.crm_meetings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_meetings.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_meeting_tasks: {
    name: 'crm_meeting_tasks',
    displayName: '회의 할 일 및 일정',
    columns: COLUMN_DEFINITIONS.crm_meeting_tasks.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_meeting_tasks.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  ai_contextual_help: {
    name: 'ai_contextual_help',
    displayName: 'AI 도움말 캐시',
    columns: COLUMN_DEFINITIONS.ai_contextual_help.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.ai_contextual_help.length,
    rowCount: 0,
    uniqueKeyColumns: ["hint_key"],
  },
  form_templates: {
    name: 'form_templates',
    displayName: '양식 템플릿 마스터',
    columns: COLUMN_DEFINITIONS.form_templates.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.form_templates.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  form_mappings: {
    name: 'form_mappings',
    displayName: '양식 데이터 필드 매핑',
    columns: COLUMN_DEFINITIONS.form_mappings.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.form_mappings.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_employment_certificate_logs: {
    name: 'crm_employment_certificate_logs',
    displayName: '재직증명서 발급대장',
    columns: COLUMN_DEFINITIONS.crm_employment_certificate_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_employment_certificate_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_web_templates: {
    name: 'crm_web_templates',
    displayName: '웹 양식 템플릿 마스터',
    columns: COLUMN_DEFINITIONS.crm_web_templates.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_web_templates.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_web_form_logs: {
    name: 'crm_web_form_logs',
    displayName: '웹 양식 발급대장',
    columns: COLUMN_DEFINITIONS.crm_web_form_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_web_form_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_web_published_sites: {
    name: 'crm_web_published_sites',
    displayName: '홈페이지 다변화 배포 관리',
    columns: COLUMN_DEFINITIONS.crm_web_published_sites.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_web_published_sites.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  easybot_action_audit_logs: {
    name: 'easybot_action_audit_logs',
    displayName: '이지봇 AI 감사 로그',
    columns: COLUMN_DEFINITIONS.easybot_action_audit_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.easybot_action_audit_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_partner_ai_reports: {
    name: 'crm_partner_ai_reports',
    displayName: '거래처 AI 리스크 보고서',
    columns: COLUMN_DEFINITIONS.crm_partner_ai_reports.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_partner_ai_reports.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  safety_policies: {
    name: 'safety_policies',
    displayName: '안전보건방침 및 목표',
    columns: COLUMN_DEFINITIONS.safety_policies.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.safety_policies.length,
    rowCount: 0,
    uniqueKeyColumns: ["year"],
    duplicateAction: 'update',
  },
  safety_risk_assessments: {
    name: 'safety_risk_assessments',
    displayName: 'AI 위험성평가서',
    columns: COLUMN_DEFINITIONS.safety_risk_assessments.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.safety_risk_assessments.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  safety_tbm_logs: {
    name: 'safety_tbm_logs',
    displayName: 'TBM 안전 교육 대장',
    columns: COLUMN_DEFINITIONS.safety_tbm_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.safety_tbm_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  safety_near_misses: {
    name: 'safety_near_misses',
    displayName: '아차사고 및 유해요소 제보 대장',
    columns: COLUMN_DEFINITIONS.safety_near_misses.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.safety_near_misses.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  safety_inspect_logs: {
    name: 'safety_inspect_logs',
    displayName: '안전점검 감사 대장',
    columns: COLUMN_DEFINITIONS.safety_inspect_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.safety_inspect_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_financial_statements: {
    name: 'crm_financial_statements',
    displayName: '재무제표 관리',
    columns: COLUMN_DEFINITIONS.crm_financial_statements.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_financial_statements.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_financial_statement_items: {
    name: 'crm_financial_statement_items',
    displayName: '재무제표 상세 계정과목',
    columns: COLUMN_DEFINITIONS.crm_financial_statement_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_financial_statement_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_financial_analysis_logs: {
    name: 'crm_financial_analysis_logs',
    displayName: 'AI 재무 분석 로그',
    columns: COLUMN_DEFINITIONS.crm_financial_analysis_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_financial_analysis_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_recruitment_applicants: {
    name: 'crm_recruitment_applicants',
    displayName: '채용 지원자 관리',
    columns: COLUMN_DEFINITIONS.crm_recruitment_applicants.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_recruitment_applicants.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_grant_announcements: {
    name: 'crm_grant_announcements',
    displayName: '정부 지원금 추천 공고',
    columns: COLUMN_DEFINITIONS.crm_grant_announcements.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_grant_announcements.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_grant_bookmarks: {
    name: 'crm_grant_bookmarks',
    displayName: '지원금 북마크',
    columns: COLUMN_DEFINITIONS.crm_grant_bookmarks.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_grant_bookmarks.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_grant_rnd_plans: {
    name: 'crm_grant_rnd_plans',
    displayName: '지원금 R&D 계획서',
    columns: COLUMN_DEFINITIONS.crm_grant_rnd_plans.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_grant_rnd_plans.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_grant_company_profile: {
    name: 'crm_grant_company_profile',
    displayName: '지원금 매칭용 기업 프로필',
    columns: COLUMN_DEFINITIONS.crm_grant_company_profile.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_grant_company_profile.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_checklist_submissions: {
    name: 'crm_quality_checklist_submissions',
    displayName: '체크리스트 제출 내역',
    columns: COLUMN_DEFINITIONS.crm_quality_checklist_submissions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_checklist_submissions.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_ncr_items: {
    name: 'crm_quality_ncr_items',
    displayName: 'NCR 부적합 내역',
    columns: COLUMN_DEFINITIONS.crm_quality_ncr_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_ncr_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_ncr_similar_cases: {
    name: 'crm_quality_ncr_similar_cases',
    displayName: '유사 NCR 사례',
    columns: COLUMN_DEFINITIONS.crm_quality_ncr_similar_cases.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_ncr_similar_cases.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_sensors_status: {
    name: 'crm_quality_sensors_status',
    displayName: '설비 센서 상태',
    columns: COLUMN_DEFINITIONS.crm_quality_sensors_status.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_sensors_status.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_sensors_contribution: {
    name: 'crm_quality_sensors_contribution',
    displayName: '센서 기여도',
    columns: COLUMN_DEFINITIONS.crm_quality_sensors_contribution.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_sensors_contribution.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_sensors_timeline: {
    name: 'crm_quality_sensors_timeline',
    displayName: '센서 시계열',
    columns: COLUMN_DEFINITIONS.crm_quality_sensors_timeline.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_sensors_timeline.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_spc_config: {
    name: 'crm_quality_spc_config',
    displayName: 'SPC 공정 제어 설정',
    columns: COLUMN_DEFINITIONS.crm_quality_spc_config.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_spc_config.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_spc_samples: {
    name: 'crm_quality_spc_samples',
    displayName: 'SPC 계측 샘플',
    columns: COLUMN_DEFINITIONS.crm_quality_spc_samples.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_spc_samples.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_spc_predictions: {
    name: 'crm_quality_spc_predictions',
    displayName: 'SPC 계측 예측',
    columns: COLUMN_DEFINITIONS.crm_quality_spc_predictions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_spc_predictions.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_spc_features: {
    name: 'crm_quality_spc_features',
    displayName: 'SPC 요인 중요도',
    columns: COLUMN_DEFINITIONS.crm_quality_spc_features.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_spc_features.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_vision_model: {
    name: 'crm_quality_vision_model',
    displayName: '품질 비전 AI 모델 상태',
    columns: COLUMN_DEFINITIONS.crm_quality_vision_model.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_vision_model.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_quality_vision_logs: {
    name: 'crm_quality_vision_logs',
    displayName: '품질 비전 판정 이력',
    columns: COLUMN_DEFINITIONS.crm_quality_vision_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_quality_vision_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_facilities: {
    name: 'crm_facilities',
    displayName: '설비 대장 관리',
    columns: COLUMN_DEFINITIONS.crm_facilities.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facilities.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_facility_checklists: {
    name: 'crm_facility_checklists',
    displayName: '설비 예방 점검 이력',
    columns: COLUMN_DEFINITIONS.crm_facility_checklists.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_checklists.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_facility_repair_logs: {
    name: 'crm_facility_repair_logs',
    displayName: '설비 수리 이력 대장',
    columns: COLUMN_DEFINITIONS.crm_facility_repair_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_repair_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_facility_repair_solutions: {
    name: 'crm_facility_repair_solutions',
    displayName: '설비 고장 해결 가이드',
    columns: COLUMN_DEFINITIONS.crm_facility_repair_solutions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_repair_solutions.length,
    rowCount: 0,
    uniqueKeyColumns: ["errorCode"],
  },
  crm_facility_predictive_summary: {
    name: 'crm_facility_predictive_summary',
    displayName: '설비 건전도 요약',
    columns: COLUMN_DEFINITIONS.crm_facility_predictive_summary.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_predictive_summary.length,
    rowCount: 0,
    uniqueKeyColumns: ["equipmentId"],
  },
  crm_facility_predictive_vibration: {
    name: 'crm_facility_predictive_vibration',
    displayName: '설비 진동 센서 이력',
    columns: COLUMN_DEFINITIONS.crm_facility_predictive_vibration.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_predictive_vibration.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_facility_predictive_fft: {
    name: 'crm_facility_predictive_fft',
    displayName: '설비 주파수 분석',
    columns: COLUMN_DEFINITIONS.crm_facility_predictive_fft.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_predictive_fft.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_facility_predictive_part_rul: {
    name: 'crm_facility_predictive_part_rul',
    displayName: '설비 부품 수명 RUL',
    columns: COLUMN_DEFINITIONS.crm_facility_predictive_part_rul.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_facility_predictive_part_rul.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  rnd_centers: {
    name: 'rnd_centers',
    displayName: '기업부설연구소 기본 정보',
    columns: COLUMN_DEFINITIONS.rnd_centers.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.rnd_centers.length,
    rowCount: 0,
    uniqueKeyColumns: ["center_id"],
  },
  rnd_staffs: {
    name: 'rnd_staffs',
    displayName: '연구원 정보 및 자격 정보',
    columns: COLUMN_DEFINITIONS.rnd_staffs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.rnd_staffs.length,
    rowCount: 0,
    uniqueKeyColumns: ["staff_id"],
  },
  rnd_spaces: {
    name: 'rnd_spaces',
    displayName: '연구 공간 자가 실사 및 Vision AI 분석 이력',
    columns: COLUMN_DEFINITIONS.rnd_spaces.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.rnd_spaces.length,
    rowCount: 0,
    uniqueKeyColumns: ["space_check_id"],
  },
  rnd_logs: {
    name: 'rnd_logs',
    displayName: 'R&D 연구개발 일지 및 AI 생성 데이터',
    columns: COLUMN_DEFINITIONS.rnd_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.rnd_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["log_id"],
  },
  rnd_compliance_alarms: {
    name: 'rnd_compliance_alarms',
    displayName: '규제 준수 모니터링 및 알림',
    columns: COLUMN_DEFINITIONS.rnd_compliance_alarms.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.rnd_compliance_alarms.length,
    rowCount: 0,
    uniqueKeyColumns: ["alarm_id"],
  },
  crm_credential_vault: {
    name: 'crm_credential_vault',
    displayName: '보안 인증 정보 금고',
    columns: COLUMN_DEFINITIONS.crm_credential_vault.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_credential_vault.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_credential_emergency_requests: {
    name: 'crm_credential_emergency_requests',
    displayName: '보안 인증 비상 요청 대장',
    columns: COLUMN_DEFINITIONS.crm_credential_emergency_requests.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_credential_emergency_requests.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_credential_audit_logs: {
    name: 'crm_credential_audit_logs',
    displayName: '보안 인증 감사록',
    columns: COLUMN_DEFINITIONS.crm_credential_audit_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_credential_audit_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  easybot_rules: {
    name: 'easybot_rules',
    displayName: '이지봇 자율 감시 규칙 대장',
    columns: COLUMN_DEFINITIONS.easybot_rules.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.easybot_rules.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  easybot_rules_history: {
    name: 'easybot_rules_history',
    displayName: '이지봇 규칙 변경 이력 대장',
    columns: COLUMN_DEFINITIONS.easybot_rules_history.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.easybot_rules_history.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_interpretation_sessions: {
    name: 'crm_interpretation_sessions',
    displayName: '실시간 통역 AI 세션',
    columns: COLUMN_DEFINITIONS.crm_interpretation_sessions.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_interpretation_sessions.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_interpretation_logs: {
    name: 'crm_interpretation_logs',
    displayName: '실시간 통역 AI 발화 로그',
    columns: COLUMN_DEFINITIONS.crm_interpretation_logs.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_interpretation_logs.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_excel_signatures: {
    name: 'crm_excel_signatures',
    displayName: '엑셀 헤더 자동 승인',
    columns: COLUMN_DEFINITIONS.crm_excel_signatures.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_excel_signatures.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  crm_inbound_excel_signatures: {
    name: 'crm_inbound_excel_signatures',
    displayName: '엑셀 입고 자동 매핑',
    columns: COLUMN_DEFINITIONS.crm_inbound_excel_signatures.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.crm_inbound_excel_signatures.length,
    rowCount: 0,
    uniqueKeyColumns: ["id"],
  },
  import_master: {
    name: 'import_master',
    displayName: '수입 발주 마스터',
    columns: COLUMN_DEFINITIONS.import_master.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.import_master.length,
    rowCount: 0,
    uniqueKeyColumns: ["so_number"],
  },
  import_items: {
    name: 'import_items',
    displayName: '수입 품목 상세',
    columns: COLUMN_DEFINITIONS.import_items.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.import_items.length,
    rowCount: 0,
    uniqueKeyColumns: ["item_id"],
  },
  import_finance: {
    name: 'import_finance',
    displayName: '수입 정산 관리',
    columns: COLUMN_DEFINITIONS.import_finance.map(c => c.name),
    columnCount: COLUMN_DEFINITIONS.import_finance.length,
    rowCount: 0,
    uniqueKeyColumns: ["finance_id"],
  },
} as const;

export type TableName = keyof typeof TABLES;
export const TABLE_NAMES = Object.keys(TABLES) as TableName[];
