"use strict";
/**
 * EGDesk Helper Functions for Next.js
 *
 * Type-safe helpers for EGDesk user data, FinanceHub (banks, cards, Hometax, promissory notes),
 * internal knowledge / business identity / company research (MCP), and browser recorder replay.
 * Works in both client and server components.
 *
 * Generated by @egdesk/next-api-plugin
 */
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.callUserDataTool = callUserDataTool;
exports.queryTable = queryTable;
exports.searchTable = searchTable;
exports.aggregateTable = aggregateTable;
exports.executeSQL = executeSQL;
exports.listTables = listTables;
exports.getTableSchema = getTableSchema;
exports.createTable = createTable;
exports.insertRows = insertRows;
exports.updateRows = updateRows;
exports.deleteRows = deleteRows;
exports.deleteTable = deleteTable;
exports.renameTable = renameTable;
exports.callFinanceHubTool = callFinanceHubTool;
exports.listBanks = listBanks;
exports.listAccounts = listAccounts;
exports.queryBankTransactions = queryBankTransactions;
exports.queryCardTransactions = queryCardTransactions;
exports.getTransactionStats = getTransactionStats;
exports.getMonthlySummary = getMonthlySummary;
exports.getOverallStats = getOverallStats;
exports.getSyncHistory = getSyncHistory;
exports.listHometaxConnections = listHometaxConnections;
exports.queryTaxInvoices = queryTaxInvoices;
exports.queryTaxExemptInvoices = queryTaxExemptInvoices;
exports.queryCashReceipts = queryCashReceipts;
exports.getHometaxSyncHistory = getHometaxSyncHistory;
exports.listBankProductTables = listBankProductTables;
exports.queryBankProductTable = queryBankProductTable;
exports.callInternalKnowledgeTool = callInternalKnowledgeTool;
exports.listKnowledgeDocuments = listKnowledgeDocuments;
exports.getKnowledgeDocument = getKnowledgeDocument;
exports.searchKnowledgeContent = searchKnowledgeContent;
exports.getKnowledgeByCategory = getKnowledgeByCategory;
exports.createKnowledgeDocument = createKnowledgeDocument;
exports.updateKnowledgeDocument = updateKnowledgeDocument;
exports.deleteKnowledgeDocument = deleteKnowledgeDocument;
exports.listBusinessIdentitySnapshots = listBusinessIdentitySnapshots;
exports.getBusinessIdentitySnapshot = getBusinessIdentitySnapshot;
exports.getBusinessIdentityCompanyInfo = getBusinessIdentityCompanyInfo;
exports.getBusinessIdentityServicesProducts = getBusinessIdentityServicesProducts;
exports.listCompanyResearch = listCompanyResearch;
exports.getCompanyResearchById = getCompanyResearchById;
exports.getCompanyResearchByDomain = getCompanyResearchByDomain;
exports.searchCompanyResearch = searchCompanyResearch;
exports.callBrowserRecordingTool = callBrowserRecordingTool;
exports.listBrowserRecordingTests = listBrowserRecordingTests;
exports.getBrowserRecordingReplayOptions = getBrowserRecordingReplayOptions;
exports.runBrowserRecording = runBrowserRecording;
exports.callAICenterTool = callAICenterTool;
exports.listDataSources = listDataSources;
exports.listWorkflows = listWorkflows;
exports.getWorkflow = getWorkflow;
exports.createWorkflow = createWorkflow;
exports.updateWorkflow = updateWorkflow;
exports.updateWorkflowStatus = updateWorkflowStatus;
exports.deleteWorkflow = deleteWorkflow;
exports.setWorkflowNotifyRoles = setWorkflowNotifyRoles;
exports.addWorkflowAction = addWorkflowAction;
exports.removeWorkflowAction = removeWorkflowAction;
exports.createRun = createRun;
exports.getRun = getRun;
exports.getRuns = getRuns;
exports.updateRunStatus = updateRunStatus;
exports.advanceRunStage = advanceRunStage;
exports.createApproval = createApproval;
exports.getApprovals = getApprovals;
exports.recordApprovalDecision = recordApprovalDecision;
exports.listEntities = listEntities;
exports.createEntity = createEntity;
exports.deleteEntity = deleteEntity;
exports.listRelations = listRelations;
exports.createRelation = createRelation;
exports.deleteRelation = deleteRelation;
exports.listTags = listTags;
exports.createTag = createTag;
exports.deleteTag = deleteTag;
exports.getCalendarEventsFromAICenter = getCalendarEventsFromAICenter;
exports.completeTask = completeTask;
var egdesk_config_1 = require("./egdesk.config");
/**
 * Parse EGDesk MCP `/tools/call` JSON so `error` is shown even when HTTP status is 500.
 */
function parseEgdeskMcpToolResponse(response) {
    return __awaiter(this, void 0, void 0, function () {
        var result, errMsg, fromBody, content;
        var _a, _b, _c;
        return __generator(this, function (_d) {
            switch (_d.label) {
                case 0: return [4 /*yield*/, response.json().catch(function () { return null; })];
                case 1:
                    result = _d.sent();
                    if (result && typeof result === 'object' && result.success === false) {
                        errMsg = typeof result.error === 'string'
                            ? result.error
                            : result.error != null
                                ? String(result.error)
                                : 'Tool call failed';
                        throw new Error(errMsg);
                    }
                    if (!response.ok) {
                        fromBody = '';
                        if (result && typeof result === 'object') {
                            if (typeof result.error === 'string')
                                fromBody = result.error;
                            else if (typeof result.message === 'string') {
                                fromBody = result.message;
                            }
                        }
                        throw new Error(fromBody || "HTTP ".concat(response.status, ": ").concat(response.statusText));
                    }
                    if (!result || result.success !== true) {
                        throw new Error(result && typeof result === 'object' && typeof result.error === 'string'
                            ? result.error
                            : 'Tool call failed');
                    }
                    content = (_c = (_b = (_a = result.result) === null || _a === void 0 ? void 0 : _a.content) === null || _b === void 0 ? void 0 : _b[0]) === null || _c === void 0 ? void 0 : _c.text;
                    return [2 /*return*/, content ? JSON.parse(content) : null];
            }
        });
    });
}
/**
 * Call EGDesk user-data MCP tool
 *
 * - Server (API routes): Calls Egdesk API directly using EGDESK_CONFIG.apiUrl and
 *   EGDESK_CONFIG.apiKey (from env NEXT_PUBLIC_EGDESK_API_URL / NEXT_PUBLIC_EGDESK_API_KEY)
 *   so relative URLs and tunnel base path are not an issue.
 * - Client (browser): Uses /__user_data_proxy so CORS and tunnel base path still work.
 */
function callUserDataTool(toolName_1) {
    return __awaiter(this, arguments, void 0, function (toolName, args) {
        var body, headers, isServer, response, apiUrl, apiKey;
        var _a, _b;
        if (args === void 0) { args = {}; }
        return __generator(this, function (_c) {
            switch (_c.label) {
                case 0:
                    body = JSON.stringify({ tool: toolName, arguments: args });
                    headers = {
                        'Content-Type': 'application/json'
                    };
                    isServer = typeof window === 'undefined';
                    if (!isServer) return [3 /*break*/, 2];
                    apiUrl = (typeof process !== 'undefined' && ((_a = process.env) === null || _a === void 0 ? void 0 : _a.NEXT_PUBLIC_EGDESK_API_URL)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiUrl;
                    apiKey = (typeof process !== 'undefined' && ((_b = process.env) === null || _b === void 0 ? void 0 : _b.NEXT_PUBLIC_EGDESK_API_KEY)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiKey;
                    if (apiKey) {
                        headers['X-Api-Key'] = apiKey;
                    }
                    var projectId = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID : undefined;
                    var egdeskEnv = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_ENV : undefined;
                    if (projectId) {
                        headers['X-EGDesk-Project-Id'] = projectId;
                    }
                    if (egdeskEnv) {
                        headers['X-EGDesk-Env'] = egdeskEnv;
                    }
                    return [4 /*yield*/, fetch("".concat(apiUrl, "/user-data/tools/call"), {
                            method: 'POST',
                            headers: headers,
                            body: body
                        })];
                case 1:
                    response = _c.sent();
                    return [3 /*break*/, 4];
                case 2: return [4 /*yield*/, fetch('/__user_data_proxy', {
                        method: 'POST',
                        headers: headers,
                        body: body
                    })];
                case 3:
                    // Browser: use proxy for CORS and tunnel base path
                    response = _c.sent();
                    _c.label = 4;
                case 4: return [2 /*return*/, parseEgdeskMcpToolResponse(response)];
            }
        });
    });
}
/**
 * Query table data
 */
function queryTable(tableName_1) {
    return __awaiter(this, arguments, void 0, function (tableName, options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_query', __assign({ tableName: tableName }, options))];
        });
    });
}
/**
 * Search table
 */
function searchTable(tableName_1, searchQuery_1) {
    return __awaiter(this, arguments, void 0, function (tableName, searchQuery, limit) {
        if (limit === void 0) { limit = 50; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_search', {
                    tableName: tableName,
                    searchQuery: searchQuery,
                    limit: limit
                })];
        });
    });
}
/**
 * Aggregate data
 */
function aggregateTable(tableName_1, column_1, aggregateFunction_1) {
    return __awaiter(this, arguments, void 0, function (tableName, column, aggregateFunction, options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_aggregate', __assign({ tableName: tableName, column: column, function: aggregateFunction }, options))];
        });
    });
}
/**
 * Execute raw SQL query (read-only, SELECT only)
 */
function executeSQL(query) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_sql_query', { query: query })];
        });
    });
}
/**
 * List all available tables
 */
function listTables() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_list_tables', {})];
        });
    });
}
/**
 * Get table schema
 */
function getTableSchema(tableName) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_get_schema', { tableName: tableName })];
        });
    });
}
/**
 * Create a new table
 */
function createTable(displayName, schema, options) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_create_table', __assign({ displayName: displayName, schema: schema }, options))];
        });
    });
}
function interceptTokenLog(tableName, rows) {
    return __awaiter(this, void 0, void 0, function () {
        var userName, menuPath, cookies_1, cookieStore, token, decodeJwt_1, payload, headers_1, headerList, referer, url;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    if (!(tableName === 'ai_token_usage_logs' && typeof window === 'undefined')) return [3 /*break*/, 9];
                    userName = '시스템';
                    menuPath = '백그라운드';
                    _a.label = 1;
                case 1:
                    _a.trys.push([1, 4, , 5]);
                    return [4 /*yield*/, Promise.resolve().then(function () { return require('next/headers'); })];
                case 2:
                    cookies_1 = _a.sent().cookies;
                    return [4 /*yield*/, cookies_1()];
                case 3:
                    cookieStore = _a.sent();
                    token = cookieStore.get('auth_token') === null || cookieStore.get('auth_token') === void 0 ? void 0 : cookieStore.get('auth_token').value;
                    if (token) {
                        decodeJwt_1 = require('jose').decodeJwt;
                        payload = decodeJwt_1(token);
                        if (payload.name)
                            userName = payload.name;
                    }
                    return [3 /*break*/, 5];
                case 4:
                    _a.sent();
                    return [3 /*break*/, 5];
                case 5:
                    _a.trys.push([5, 8, , 9]);
                    return [4 /*yield*/, Promise.resolve().then(function () { return require('next/headers'); })];
                case 6:
                    headers_1 = _a.sent().headers;
                    return [4 /*yield*/, headers_1()];
                case 7:
                    headerList = _a.sent();
                    referer = headerList.get('referer');
                    if (referer) {
                        try {
                            url = new URL(referer);
                            menuPath = url.pathname;
                        }
                        catch (urlErr) {
                            menuPath = referer;
                        }
                    }
                    return [3 /*break*/, 9];
                case 8:
                    _a.sent();
                    return [3 /*break*/, 9];
                case 9:
                    rows = rows.map(function (row) {
                        return __assign(__assign({}, row), { user_name: row.user_name || userName, menu_path: row.menu_path || menuPath });
                    });
                    _a.label = 10;
                case 10: return [2 /*return*/, rows];
            }
        });
    });
}
/**
 * Insert rows into a table
 */
function insertRows(tableName, rows) {
    return __awaiter(this, void 0, void 0, function () {
        var res;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    if (typeof window === 'undefined' && false) { // 로컬 DB 직접 접근 비활성화 (항상 MCP API 사용)
                        try {
                            const os = require('os');
                            const path = require('path');
                            const fs = require('fs');
                            const homeDir = os.homedir();
                            const appData = process.env.APPDATA || path.join(homeDir, 'AppData/Roaming');
                            const paths = [
                                path.join(appData, 'EGDesk/database/user_data.db'),
                                path.join(appData, 'egdesk/database/user_data.db')
                            ];
                            let targetPath = '';
                            for (const p of paths) {
                                if (fs.existsSync(p)) {
                                    targetPath = p;
                                    break;
                                }
                            }
                            if (!targetPath) {
                                targetPath = paths[0];
                            }
                            const normalizedPath = targetPath.replace(/\\/g, '/');
                            if (fs.existsSync(normalizedPath)) {
                                const Database = require('better-sqlite3');
                                const db = new Database(normalizedPath);
                                db.transaction(() => {
                                    for (const row of rows) {
                                        const keys = Object.keys(row);
                                        const columns = keys.join(', ');
                                        const placeholders = keys.map(() => '?').join(', ');
                                        const sql = `INSERT INTO ${tableName} (${columns}) VALUES (${placeholders})`;
                                        db.prepare(sql).run(...keys.map(k => row[k]));
                                    }
                                })();
                                db.close();
                                res = { success: true };
                                try {
                                    const { emitDbChange } = require('./src/lib/db-event-hub');
                                    const timestamp = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().replace('T', ' ').slice(0, 19);
                                    rows.forEach(row => {
                                        emitDbChange({
                                            table: tableName,
                                            action: 'insert',
                                            timestamp: timestamp,
                                            data: row
                                        }).catch(err => console.error('[Helpers DB Event Trigger Error]:', err));
                                    });
                                } catch (e) {}
                                return [2 /*return*/, res];
                            }
                        } catch (err) {
                            console.error('Direct DB insert failed in egdesk-helpers, falling back to MCP:', err);
                        }
                    }
                    return [4 /*yield*/, interceptTokenLog(tableName, rows)];
                case 1:
                    rows = _a.sent();
                    return [4 /*yield*/, callUserDataTool('user_data_insert_rows', {
                            tableName: tableName,
                            rows: rows
                        })];
                case 2:
                    res = _a.sent();
                    // 🕒 DB 변경 이벤트 발행
                    try {
                        const { emitDbChange } = require('./src/lib/db-event-hub');
                        const timestamp = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().replace('T', ' ').slice(0, 19);
                        rows.forEach(row => {
                            emitDbChange({
                                table: tableName,
                                action: 'insert',
                                timestamp: timestamp,
                                data: row
                            }).catch(err => console.error('[Helpers DB Event Trigger Error]:', err));
                        });
                    } catch (e) {
                        console.error('[Helpers DB Event Require Error]:', e);
                    }
                    return [2 /*return*/, res];
            }
        });
    });
}
/**
 * Update rows in a table
 */
function updateRows(tableName, updates, options) {
    return __awaiter(this, void 0, void 0, function () {
        var res;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    if (typeof window === 'undefined' && false) { // 로컬 DB 직접 접근 비활성화 (항상 MCP API 사용)
                        try {
                            const os = require('os');
                            const path = require('path');
                            const fs = require('fs');
                            const homeDir = os.homedir();
                            const appData = process.env.APPDATA || path.join(homeDir, 'AppData/Roaming');
                            const paths = [
                                path.join(appData, 'EGDesk/database/user_data.db'),
                                path.join(appData, 'egdesk/database/user_data.db')
                            ];
                            let targetPath = '';
                            for (const p of paths) {
                                if (fs.existsSync(p)) {
                                    targetPath = p;
                                    break;
                                }
                            }
                            if (!targetPath) {
                                targetPath = paths[0];
                            }
                            const normalizedPath = targetPath.replace(/\\/g, '/');
                            if (fs.existsSync(normalizedPath)) {
                                const Database = require('better-sqlite3');
                                const db = new Database(normalizedPath);
                                const keys = Object.keys(updates);
                                const setClause = keys.map(k => `${k} = ?`).join(', ');
                                const params = keys.map(k => updates[k]);
                                let whereClause = '';
                                if (options.ids && options.ids.length > 0) {
                                    whereClause = `id IN (${options.ids.map(() => '?').join(', ')})`;
                                    params.push(...options.ids);
                                } else if (options.filters && Object.keys(options.filters).length > 0) {
                                    const filterKeys = Object.keys(options.filters);
                                    whereClause = filterKeys.map(k => `${k} = ?`).join(' AND ');
                                    params.push(...filterKeys.map(k => options.filters[k]));
                                }
                                if (whereClause) {
                                    const sql = `UPDATE ${tableName} SET ${setClause} WHERE ${whereClause}`;
                                    db.prepare(sql).run(...params);
                                    db.close();
                                    res = { success: true };
                                    try {
                                        const { emitDbChange } = require('./src/lib/db-event-hub');
                                        const timestamp = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().replace('T', ' ').slice(0, 19);
                                        emitDbChange({
                                            table: tableName,
                                            action: 'update',
                                            timestamp: timestamp,
                                            data: updates,
                                            previousData: options
                                        }).catch(err => console.error('[Helpers DB Event Trigger Error]:', err));
                                    } catch (e) {}
                                    return [2 /*return*/, res];
                                }
                                db.close();
                            }
                        } catch (err) {
                            console.error('Direct DB update failed in egdesk-helpers, falling back to MCP:', err);
                        }
                    }
                    return [4 /*yield*/, callUserDataTool('user_data_update_rows', __assign({ tableName: tableName, updates: updates }, options))];
                case 1:
                    res = _a.sent();
                    // 🕒 DB 변경 이벤트 발행
                    try {
                        const { emitDbChange } = require('./src/lib/db-event-hub');
                        const timestamp = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().replace('T', ' ').slice(0, 19);
                        emitDbChange({
                            table: tableName,
                            action: 'update',
                            timestamp: timestamp,
                            data: updates,
                            previousData: options
                        }).catch(err => console.error('[Helpers DB Event Trigger Error]:', err));
                    } catch (e) {
                        // 브라우저 예외 방어
                    }
                    return [2 /*return*/, res];
            }
        });
    });
}
/**
 * Delete rows from a table
 */
function deleteRows(tableName, options) {
    return __awaiter(this, void 0, void 0, function () {
        var res;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, callUserDataTool('user_data_delete_rows', __assign({ tableName: tableName }, options))];
                case 1:
                    res = _a.sent();
                    // 🕒 DB 변경 이벤트 발행
                    try {
                        const { emitDbChange } = require('./src/lib/db-event-hub');
                        const timestamp = new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString().replace('T', ' ').slice(0, 19);
                        emitDbChange({
                            table: tableName,
                            action: 'delete',
                            timestamp: timestamp,
                            data: options
                        }).catch(err => console.error('[Helpers DB Event Trigger Error]:', err));
                    } catch (e) {
                        // 브라우저 예외 방어
                    }
                    return [2 /*return*/, res];
            }
        });
    });
}
/**
 * Delete a table
 */
function deleteTable(tableName) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_delete_table', { tableName: tableName })];
        });
    });
}
/**
 * Rename a table
 */
function renameTable(tableName, newTableName, newDisplayName) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callUserDataTool('user_data_rename_table', {
                    tableName: tableName,
                    newTableName: newTableName,
                    newDisplayName: newDisplayName
                })];
        });
    });
}
// ==========================================
// FINANCEHUB HELPERS
// ==========================================
/**
 * Call EGDesk FinanceHub MCP tool
 */
function callFinanceHubTool(toolName_1) {
    return __awaiter(this, arguments, void 0, function (toolName, args) {
        var body, headers, isServer, response, apiUrl, apiKey;
        var _a, _b;
        if (args === void 0) { args = {}; }
        return __generator(this, function (_c) {
            switch (_c.label) {
                case 0:
                    body = JSON.stringify({ tool: toolName, arguments: args });
                    headers = {
                        'Content-Type': 'application/json'
                    };
                    isServer = typeof window === 'undefined';
                    if (!isServer) return [3 /*break*/, 2];
                    apiUrl = (typeof process !== 'undefined' && ((_a = process.env) === null || _a === void 0 ? void 0 : _a.NEXT_PUBLIC_EGDESK_API_URL)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiUrl;
                    apiKey = (typeof process !== 'undefined' && ((_b = process.env) === null || _b === void 0 ? void 0 : _b.NEXT_PUBLIC_EGDESK_API_KEY)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiKey;
                    if (apiKey) {
                        headers['X-Api-Key'] = apiKey;
                    }
                    var projectId = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID : undefined;
                    var egdeskEnv = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_ENV : undefined;
                    if (projectId) {
                        headers['X-EGDesk-Project-Id'] = projectId;
                    }
                    if (egdeskEnv) {
                        headers['X-EGDesk-Env'] = egdeskEnv;
                    }
                    return [4 /*yield*/, fetch("".concat(apiUrl, "/financehub/tools/call"), {
                            method: 'POST',
                            headers: headers,
                            body: body
                        })];
                case 1:
                    response = _c.sent();
                    return [3 /*break*/, 4];
                case 2: return [4 /*yield*/, fetch('/__financehub_proxy', {
                        method: 'POST',
                        headers: headers,
                        body: body
                    })];
                case 3:
                    response = _c.sent();
                    _c.label = 4;
                case 4: return [2 /*return*/, parseEgdeskMcpToolResponse(response)];
            }
        });
    });
}
/**
 * List all registered banks and card companies
 */
function listBanks() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_list_banks', {})];
        });
    });
}
/**
 * List bank accounts with balances
 */
function listAccounts() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_list_accounts', options)];
        });
    });
}
/**
 * Query bank transactions
 */
function queryBankTransactions() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_query_transactions', options)];
        });
    });
}
/**
 * Query card transactions (NEW)
 */
function queryCardTransactions() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_query_card_transactions', options)];
        });
    });
}
/**
 * Get transaction statistics
 */
function getTransactionStats() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_get_statistics', options)];
        });
    });
}
/**
 * Get monthly breakdown of deposits/withdrawals
 */
function getMonthlySummary() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_get_monthly_summary', options)];
        });
    });
}
/**
 * Get overall stats (banks, accounts, transactions, balances)
 */
function getOverallStats() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_get_overall_stats', {})];
        });
    });
}
/**
 * Get bank/card sync operation history (sync_operations table)
 */
function getSyncHistory() {
    return __awaiter(this, arguments, void 0, function (limit) {
        if (limit === void 0) { limit = 50; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_get_sync_history', { limit: limit })];
        });
    });
}
/**
 * List Hometax business connections (hometax_connections: counts, spreadsheet URLs, status)
 */
function listHometaxConnections() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_list_hometax_connections', {})];
        });
    });
}
/**
 * Query electronic tax invoices synced from Hometax (tax_invoices table)
 */
function queryTaxInvoices() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_query_tax_invoices', options)];
        });
    });
}
/**
 * Query tax-exempt invoices synced from Hometax (tax_exempt_invoices table)
 */
function queryTaxExemptInvoices() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_query_tax_exempt_invoices', options)];
        });
    });
}
/**
 * Query cash receipts synced from Hometax (cash_receipts table)
 */
function queryCashReceipts() {
    return __awaiter(this, arguments, void 0, function (options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_query_cash_receipts', options)];
        });
    });
}
/**
 * Get Hometax Excel import sync history (hometax_sync_operations). Not the same as getSyncHistory (banks/cards).
 */
function getHometaxSyncHistory() {
    return __awaiter(this, arguments, void 0, function (limit) {
        if (limit === void 0) { limit = 50; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_get_hometax_sync_history', { limit: limit })];
        });
    });
}
/**
 * List per-(bank, product) bank-product tables — bank-side product data
 * downloaded from bank portals that isn't core deposit/card transactions
 * (loans, receivables, e-bills, etc.). Returns table slugs, displayName,
 * column schemas, and row counts. ALWAYS call this first to discover
 * what tables exist before calling queryBankProductTable.
 */
function listBankProductTables() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_list_bank_product_tables', {})];
        });
    });
}
/**
 * Generic safe query against any per-(bank, product) table from
 * listBankProductTables. Filters use the table's exact column names
 * (snake_case). Returns rows with totalMatching, limit, offset.
 *
 * @example
 *   queryBankProductTable({
 *     tableSlug: 'ibk_loan_transactions',
 *     filters: [
 *       { column: 'account_number', op: '=', value: '306-063568-04-036' },
 *       { column: 'transaction_amount', op: '>', value: 1000000 },
 *     ],
 *     orderBy: { column: 'transaction_date', direction: 'DESC' },
 *     limit: 50,
 *   });
 */
function queryBankProductTable(options) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callFinanceHubTool('financehub_query_bank_product_table', options)];
        });
    });
}
// ==========================================
// INTERNAL KNOWLEDGE / BUSINESS IDENTITY / COMPANY RESEARCH (MCP)
// ==========================================
/**
 * Call EGDesk Internal Knowledge MCP tool (knowledge docs, business identity snapshots, company research).
 *
 * - Server: `POST {apiUrl}/internal-knowledge/tools/call`
 * - Client: `POST /__internal_knowledge_proxy` (see proxy.ts / middleware)
 */
function callInternalKnowledgeTool(toolName_1) {
    return __awaiter(this, arguments, void 0, function (toolName, args) {
        var body, headers, isServer, response, apiUrl, apiKey;
        var _a, _b;
        if (args === void 0) { args = {}; }
        return __generator(this, function (_c) {
            switch (_c.label) {
                case 0:
                    body = JSON.stringify({ tool: toolName, arguments: args });
                    headers = {
                        'Content-Type': 'application/json'
                    };
                    isServer = typeof window === 'undefined';
                    if (!isServer) return [3 /*break*/, 2];
                    apiUrl = (typeof process !== 'undefined' && ((_a = process.env) === null || _a === void 0 ? void 0 : _a.NEXT_PUBLIC_EGDESK_API_URL)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiUrl;
                    apiKey = (typeof process !== 'undefined' && ((_b = process.env) === null || _b === void 0 ? void 0 : _b.NEXT_PUBLIC_EGDESK_API_KEY)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiKey;
                    if (apiKey) {
                        headers['X-Api-Key'] = apiKey;
                    }
                    var projectId = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID : undefined;
                    var egdeskEnv = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_ENV : undefined;
                    if (projectId) {
                        headers['X-EGDesk-Project-Id'] = projectId;
                    }
                    if (egdeskEnv) {
                        headers['X-EGDesk-Env'] = egdeskEnv;
                    }
                    return [4 /*yield*/, fetch("".concat(apiUrl, "/internal-knowledge/tools/call"), {
                            method: 'POST',
                            headers: headers,
                            body: body
                        })];
                case 1:
                    response = _c.sent();
                    return [3 /*break*/, 4];
                case 2: return [4 /*yield*/, fetch('/__internal_knowledge_proxy', {
                        method: 'POST',
                        headers: headers,
                        body: body
                    })];
                case 3:
                    response = _c.sent();
                    _c.label = 4;
                case 4: return [2 /*return*/, parseEgdeskMcpToolResponse(response)];
            }
        });
    });
}
/** List internal knowledge documents for a business identity snapshot */
function listKnowledgeDocuments(snapshotId, category) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_list_documents', __assign({ snapshotId: snapshotId }, (category != null ? { category: category } : {})))];
        });
    });
}
/** Get one knowledge document by ID (full markdown content) */
function getKnowledgeDocument(documentId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_get_document', { documentId: documentId })];
        });
    });
}
/** Search knowledge documents by text in title or content */
function searchKnowledgeContent(snapshotId, searchText, category) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_search_content', __assign({ snapshotId: snapshotId, searchText: searchText }, (category != null ? { category: category } : {})))];
        });
    });
}
/** Get all documents of a single category for a snapshot */
function getKnowledgeByCategory(snapshotId, category) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_get_by_category', { snapshotId: snapshotId, category: category })];
        });
    });
}
/** Create a new knowledge document */
function createKnowledgeDocument(snapshotId, title, category, content) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_create_document', __assign({ snapshotId: snapshotId, title: title, category: category }, (content != null ? { content: content } : {})))];
        });
    });
}
/** Update an existing knowledge document */
function updateKnowledgeDocument(documentId, updates) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_update_document', __assign({ documentId: documentId }, updates))];
        });
    });
}
/** Delete a knowledge document */
function deleteKnowledgeDocument(documentId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('knowledge_delete_document', { documentId: documentId })];
        });
    });
}
/** List business identity snapshots (optional brand filter) */
function listBusinessIdentitySnapshots(brandKey) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('businessidentity_list_snapshots', __assign({}, (brandKey != null ? { brandKey: brandKey } : {})))];
        });
    });
}
/** Full snapshot by ID (identity JSON, SEO/SSL analysis, etc.) */
function getBusinessIdentitySnapshot(snapshotId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('businessidentity_get_snapshot', { snapshotId: snapshotId })];
        });
    });
}
/** Company info slice from a snapshot (contact, structure, partners, industries) */
function getBusinessIdentityCompanyInfo(snapshotId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('businessidentity_get_company_info', { snapshotId: snapshotId })];
        });
    });
}
/** Services and products from a snapshot */
function getBusinessIdentityServicesProducts(snapshotId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('businessidentity_get_services_products', { snapshotId: snapshotId })];
        });
    });
}
/** List company research records */
function listCompanyResearch(status) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('companyresearch_list_all', __assign({}, (status != null ? { status: status } : {})))];
        });
    });
}
/** One company research record by ID */
function getCompanyResearchById(researchId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('companyresearch_get_by_id', { researchId: researchId })];
        });
    });
}
/** Research records for a domain */
function getCompanyResearchByDomain(domain) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('companyresearch_get_by_domain', { domain: domain })];
        });
    });
}
/** Search company research by company name or domain */
function searchCompanyResearch(searchText) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callInternalKnowledgeTool('companyresearch_search', { searchText: searchText })];
        });
    });
}
// ==========================================
// BROWSER RECORDING HELPERS
// ==========================================
/**
 * Call EGDesk Browser Recording MCP tool (saved recorder tests, replay with optional dates).
 *
 * - Server: `POST {apiUrl}/browser-recording/tools/call`
 * - Client: `POST /__browser_recording_proxy` (see proxy.ts / middleware)
 */
function callBrowserRecordingTool(toolName_1) {
    return __awaiter(this, arguments, void 0, function (toolName, args) {
        var body, headers, isServer, response, apiUrl, apiKey;
        var _a, _b;
        if (args === void 0) { args = {}; }
        return __generator(this, function (_c) {
            switch (_c.label) {
                case 0:
                    body = JSON.stringify({ tool: toolName, arguments: args });
                    headers = {
                        'Content-Type': 'application/json'
                    };
                    isServer = typeof window === 'undefined';
                    if (!isServer) return [3 /*break*/, 2];
                    apiUrl = (typeof process !== 'undefined' && ((_a = process.env) === null || _a === void 0 ? void 0 : _a.NEXT_PUBLIC_EGDESK_API_URL)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiUrl;
                    apiKey = (typeof process !== 'undefined' && ((_b = process.env) === null || _b === void 0 ? void 0 : _b.NEXT_PUBLIC_EGDESK_API_KEY)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiKey;
                    if (apiKey) {
                        headers['X-Api-Key'] = apiKey;
                    }
                    var projectId = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID : undefined;
                    var egdeskEnv = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_ENV : undefined;
                    if (projectId) {
                        headers['X-EGDesk-Project-Id'] = projectId;
                    }
                    if (egdeskEnv) {
                        headers['X-EGDesk-Env'] = egdeskEnv;
                    }
                    return [4 /*yield*/, fetch("".concat(apiUrl, "/browser-recording/tools/call"), {
                            method: 'POST',
                            headers: headers,
                            body: body
                        })];
                case 1:
                    response = _c.sent();
                    return [3 /*break*/, 4];
                case 2: return [4 /*yield*/, fetch('/__browser_recording_proxy', {
                        method: 'POST',
                        headers: headers,
                        body: body
                    })];
                case 3:
                    response = _c.sent();
                    _c.label = 4;
                case 4: return [2 /*return*/, parseEgdeskMcpToolResponse(response)];
            }
        });
    });
}
/** List saved *.spec.js files in the EGDesk browser-recorder-tests output folder */
function listBrowserRecordingTests() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callBrowserRecordingTool('browser_recording_list_saved_tests', {})];
        });
    });
}
/** Inspect a spec: date UI, defaultReplayDates, labeledFieldReplayBlocks, etc. */
function getBrowserRecordingReplayOptions(testFile) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callBrowserRecordingTool('browser_recording_get_replay_options', { testFile: testFile })];
        });
    });
}
/** Replay a saved recording in Chrome (optional dates + labeledFieldFills) */
function runBrowserRecording(testFile_1) {
    return __awaiter(this, arguments, void 0, function (testFile, options) {
        if (options === void 0) { options = {}; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callBrowserRecordingTool('browser_recording_run', __assign({ testFile: testFile }, options))];
        });
    });
}
// ==========================================
// AI CENTER (workflows, entities, relations, tags)
// ==========================================
/**
 * Call EGDesk AI Center MCP tool (workflows, Neuron Layer entities/relations/tags).
 *
 * - Server: `POST {apiUrl}/ai-center/tools/call`
 * - Client: `POST /__ai_center_proxy` (see proxy.ts / middleware)
 */
function callAICenterTool(toolName_1) {
    return __awaiter(this, arguments, void 0, function (toolName, args) {
        var body, headers, isServer, response, apiUrl, apiKey;
        var _a, _b;
        if (args === void 0) { args = {}; }
        return __generator(this, function (_c) {
            switch (_c.label) {
                case 0:
                    body = JSON.stringify({ tool: toolName, arguments: args });
                    headers = {
                        'Content-Type': 'application/json'
                    };
                    isServer = typeof window === 'undefined';
                    if (!isServer) return [3 /*break*/, 2];
                    apiUrl = (typeof process !== 'undefined' && ((_a = process.env) === null || _a === void 0 ? void 0 : _a.NEXT_PUBLIC_EGDESK_API_URL)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiUrl;
                    apiKey = (typeof process !== 'undefined' && ((_b = process.env) === null || _b === void 0 ? void 0 : _b.NEXT_PUBLIC_EGDESK_API_KEY)) ||
                        egdesk_config_1.EGDESK_CONFIG.apiKey;
                    if (apiKey) {
                        headers['X-Api-Key'] = apiKey;
                    }
                    var projectId = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID : undefined;
                    var egdeskEnv = typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_EGDESK_ENV : undefined;
                    if (projectId) {
                        headers['X-EGDesk-Project-Id'] = projectId;
                    }
                    if (egdeskEnv) {
                        headers['X-EGDesk-Env'] = egdeskEnv;
                    }
                    return [4 /*yield*/, fetch("".concat(apiUrl, "/ai-center/tools/call"), {
                            method: 'POST',
                            headers: headers,
                            body: body
                        })];
                case 1:
                    response = _c.sent();
                    return [3 /*break*/, 4];
                case 2: return [4 /*yield*/, fetch('/__ai_center_proxy', {
                        method: 'POST',
                        headers: headers,
                        body: body
                    })];
                case 3:
                    response = _c.sent();
                    _c.label = 4;
                case 4: return [2 /*return*/, parseEgdeskMcpToolResponse(response)];
            }
        });
    });
}
// ── Data Sources ─────────────────────────────────────────────────────────────
/**
 * List all data sources available for AI processing (user data tables, finance hub accounts,
 * business identity snapshots, company research records) with processing state.
 */
function listDataSources() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_list_data_sources', {})];
        });
    });
}
// ── Workflows ────────────────────────────────────────────────────────────────
/** List all AI workflows */
function listWorkflows() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_list_workflows', {})];
        });
    });
}
/** Get a single workflow by ID (includes action steps) */
function getWorkflow(id) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_get_workflow', { id: id })];
        });
    });
}
/** Create a new AI workflow */
function createWorkflow(data) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_create_workflow', data)];
        });
    });
}
/** Update metadata fields of an existing workflow */
function updateWorkflow(id, data) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_update_workflow', __assign({ id: id }, data))];
        });
    });
}
/** Change the status of a workflow */
function updateWorkflowStatus(id, status) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_update_workflow_status', { id: id, status: status })];
        });
    });
}
/** Delete a workflow and all its action steps */
function deleteWorkflow(id) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_delete_workflow', { id: id })];
        });
    });
}
// ── Workflow notify roles ─────────────────────────────────────────────────────
/** Set which roles receive notifications for all activity on a workflow's runs */
function setWorkflowNotifyRoles(workflowId, roles) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_set_workflow_notify', { workflowId: workflowId, roles: roles })];
        });
    });
}
// ── Workflow actions ──────────────────────────────────────────────────────────
/** Append or insert an action step into a workflow */
function addWorkflowAction(workflowId_1, actionId_1, params_1) {
    return __awaiter(this, arguments, void 0, function (workflowId, actionId, params, stage, position) {
        if (stage === void 0) { stage = 0; }
        if (position === void 0) { position = 0; }
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_add_workflow_action', { workflowId: workflowId, actionId: actionId, params: params, stage: stage, position: position })];
        });
    });
}
/** Remove a single action step from a workflow by its row ID */
function removeWorkflowAction(rowId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_remove_workflow_action', { rowId: rowId })];
        });
    });
}
// ── Workflow runs ─────────────────────────────────────────────────────────────
/** Start a new run of a workflow, optionally linked to a source data row */
function createRun(workflowId, inputData, sourceTable, sourceRowId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_create_run', { workflowId: workflowId, inputData: inputData, sourceTable: sourceTable, sourceRowId: sourceRowId })];
        });
    });
}
/** Get a single workflow run by ID */
function getRun(runId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_get_run', { runId: runId })];
        });
    });
}
/** Get all runs for a workflow */
function getRuns(workflowId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_get_runs', { workflowId: workflowId })];
        });
    });
}
/** Update the status of a workflow run */
function updateRunStatus(runId, status) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_update_run_status', { runId: runId, status: status })];
        });
    });
}
/** Advance a workflow run to a new stage */
function advanceRunStage(runId, stage) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_advance_run_stage', { runId: runId, stage: stage })];
        });
    });
}
// ── Workflow approvals ────────────────────────────────────────────────────────
/** Create a pending approval record for a run */
function createApproval(runId, stage, chainPosition, role) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_create_approval', { runId: runId, stage: stage, chainPosition: chainPosition, role: role })];
        });
    });
}
/** Get all approval records for a run */
function getApprovals(runId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_get_approvals', { runId: runId })];
        });
    });
}
/** Record an approval decision */
function recordApprovalDecision(approvalId, decision) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_record_approval_decision', { approvalId: approvalId, decision: decision })];
        });
    });
}
// ── Entities ──────────────────────────────────────────────────────────────────
/** List all Neuron Layer entities, optionally filtered by type */
function listEntities(types) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_list_entities', types ? { types: types } : {})];
        });
    });
}
/** Create a new entity in the Neuron Layer */
function createEntity(data) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_create_entity', data)];
        });
    });
}
/** Delete an entity from the Neuron Layer */
function deleteEntity(id) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_delete_entity', { id: id })];
        });
    });
}
// ── Relations ─────────────────────────────────────────────────────────────────
/** List all relations, optionally filtered by source entity ID */
function listRelations(fromId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_list_relations', fromId ? { fromId: fromId } : {})];
        });
    });
}
/** Create a relation edge between two entities */
function createRelation(data) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_create_relation', data)];
        });
    });
}
/** Delete a relation edge by ID */
function deleteRelation(id) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_delete_relation', { id: id })];
        });
    });
}
// ── Tags ──────────────────────────────────────────────────────────────────────
/** List all tags, optionally filtered by entity ID */
function listTags(entityId) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_list_tags', entityId ? { entityId: entityId } : {})];
        });
    });
}
/** Create a tag/property on an entity or document */
function createTag(data) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_create_tag', data)];
        });
    });
}
/** Delete a tag by ID */
function deleteTag(id) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_delete_tag', { id: id })];
        });
    });
}
/** List all company-wide shared business deadlines from the company calendar (company_calendar table). */
function getCalendarEventsFromAICenter() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_get_calendar_events', {})];
        });
    });
}
/** Update the status of an operational task. */
function completeTask(taskId, status) {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/, callAICenterTool('ai_center_complete_task', { taskId: taskId, status: status })];
        });
    });
}
