"use strict";
/**
 * EGDesk Helper Functions for Next.js
 *
 * Type-safe helpers for EGDesk user data, FinanceHub (banks, cards, Hometax, promissory notes),
 * internal knowledge / business identity / company research (MCP), Korean law (MCP), and browser recorder replay.
 * Works in both client and server components.
 *
 * Generated by @egdesk/next-api-plugin
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.callUserDataTool = callUserDataTool;
exports.queryTable = queryTable;
exports.searchTable = searchTable;
exports.aggregateTable = aggregateTable;
exports.executeSQL = executeSQL;
exports.listTables = listTables;
exports.getTableSchema = getTableSchema;
exports.createTable = createTable;
exports.insertRows = insertRows;
exports.updateRows = updateRows;
exports.deleteRows = deleteRows;
exports.deleteTable = deleteTable;
exports.renameTable = renameTable;
exports.callFinanceHubTool = callFinanceHubTool;
exports.listBanks = listBanks;
exports.listAccounts = listAccounts;
exports.queryBankTransactions = queryBankTransactions;
exports.queryCardTransactions = queryCardTransactions;
exports.getTransactionStats = getTransactionStats;
exports.getMonthlySummary = getMonthlySummary;
exports.getOverallStats = getOverallStats;
exports.getSyncHistory = getSyncHistory;
exports.listHometaxConnections = listHometaxConnections;
exports.queryTaxInvoices = queryTaxInvoices;
exports.queryTaxExemptInvoices = queryTaxExemptInvoices;
exports.queryCashReceipts = queryCashReceipts;
exports.getHometaxSyncHistory = getHometaxSyncHistory;
exports.listBankProductTables = listBankProductTables;
exports.queryBankProductTable = queryBankProductTable;
exports.upsertFinanceHubAccount = upsertFinanceHubAccount;
exports.importFinanceHubTransactions = importFinanceHubTransactions;
exports.upsertFinanceHubBankProductRows = upsertFinanceHubBankProductRows;
exports.deleteFinanceHubAccount = deleteFinanceHubAccount;
exports.deleteFinanceHubImportedDataForBank = deleteFinanceHubImportedDataForBank;
exports.deleteFinanceHubTransactions = deleteFinanceHubTransactions;
exports.deleteFinanceHubBankProductRows = deleteFinanceHubBankProductRows;
exports.callInternalKnowledgeTool = callInternalKnowledgeTool;
exports.listKnowledgeDocuments = listKnowledgeDocuments;
exports.getKnowledgeDocument = getKnowledgeDocument;
exports.searchKnowledgeContent = searchKnowledgeContent;
exports.getKnowledgeByCategory = getKnowledgeByCategory;
exports.createKnowledgeDocument = createKnowledgeDocument;
exports.updateKnowledgeDocument = updateKnowledgeDocument;
exports.deleteKnowledgeDocument = deleteKnowledgeDocument;
exports.listBusinessIdentitySnapshots = listBusinessIdentitySnapshots;
exports.getBusinessIdentitySnapshot = getBusinessIdentitySnapshot;
exports.getBusinessIdentityCompanyInfo = getBusinessIdentityCompanyInfo;
exports.getBusinessIdentityServicesProducts = getBusinessIdentityServicesProducts;
exports.listCompanyResearch = listCompanyResearch;
exports.getCompanyResearchById = getCompanyResearchById;
exports.getCompanyResearchByDomain = getCompanyResearchByDomain;
exports.searchCompanyResearch = searchCompanyResearch;
exports.callBrowserRecordingTool = callBrowserRecordingTool;
exports.listBrowserRecordingTests = listBrowserRecordingTests;
exports.getBrowserRecordingReplayOptions = getBrowserRecordingReplayOptions;
exports.runBrowserRecording = runBrowserRecording;
exports.listBrowserRecordingSchedules = listBrowserRecordingSchedules;
exports.getBrowserRecordingSchedule = getBrowserRecordingSchedule;
exports.setBrowserRecordingSchedule = setBrowserRecordingSchedule;
exports.removeBrowserRecordingSchedule = removeBrowserRecordingSchedule;
exports.pauseBrowserRecordingSchedule = pauseBrowserRecordingSchedule;
exports.resumeBrowserRecordingSchedule = resumeBrowserRecordingSchedule;
exports.listBrowserRecordingDownloadFolders = listBrowserRecordingDownloadFolders;
exports.listBrowserRecordingSyncConfigs = listBrowserRecordingSyncConfigs;
exports.getBrowserRecordingSyncConfig = getBrowserRecordingSyncConfig;
exports.setBrowserRecordingSyncConfig = setBrowserRecordingSyncConfig;
exports.removeBrowserRecordingSyncConfig = removeBrowserRecordingSyncConfig;
exports.callAICenterTool = callAICenterTool;
exports.listDataSources = listDataSources;
exports.listWorkflows = listWorkflows;
exports.getWorkflow = getWorkflow;
exports.createWorkflow = createWorkflow;
exports.updateWorkflow = updateWorkflow;
exports.updateWorkflowStatus = updateWorkflowStatus;
exports.deleteWorkflow = deleteWorkflow;
exports.setWorkflowNotifyRoles = setWorkflowNotifyRoles;
exports.addWorkflowAction = addWorkflowAction;
exports.removeWorkflowAction = removeWorkflowAction;
exports.createRun = createRun;
exports.getRun = getRun;
exports.getRuns = getRuns;
exports.updateRunStatus = updateRunStatus;
exports.advanceRunStage = advanceRunStage;
exports.createApproval = createApproval;
exports.getApprovals = getApprovals;
exports.recordApprovalDecision = recordApprovalDecision;
exports.listEntities = listEntities;
exports.createEntity = createEntity;
exports.deleteEntity = deleteEntity;
exports.listRelations = listRelations;
exports.createRelation = createRelation;
exports.deleteRelation = deleteRelation;
exports.listTags = listTags;
exports.createTag = createTag;
exports.deleteTag = deleteTag;
exports.getCalendarEventsFromAICenter = getCalendarEventsFromAICenter;
exports.completeTask = completeTask;
exports.callKoreanLawTool = callKoreanLawTool;
exports.searchKoreanLaw = searchKoreanLaw;
exports.getKoreanLawText = getKoreanLawText;
exports.getKoreanLawDecision = getKoreanLawDecision;
const egdesk_config_1 = require("./egdesk.config");
/**
 * Parse EGDesk MCP `/tools/call` JSON so `error` is shown even when HTTP status is 500.
 */
async function parseEgdeskMcpToolResponse(response) {
    const result = await response.json().catch(() => null);
    if (result && typeof result === 'object' && result.success === false) {
        const errMsg = typeof result.error === 'string'
            ? result.error
            : result.error != null
                ? String(result.error)
                : 'Tool call failed';
        throw new Error(errMsg);
    }
    if (!response.ok) {
        let fromBody = '';
        if (result && typeof result === 'object') {
            if (typeof result.error === 'string')
                fromBody = result.error;
            else if (typeof result.message === 'string') {
                fromBody = result.message;
            }
        }
        throw new Error(fromBody || `HTTP ${response.status}: ${response.statusText}`);
    }
    if (!result || result.success !== true) {
        throw new Error(result && typeof result === 'object' && typeof result.error === 'string'
            ? result.error
            : 'Tool call failed');
    }
    const content = result.result?.content?.[0]?.text;
    return content ? JSON.parse(content) : null;
}
/**
 * Call EGDesk user-data MCP tool
 *
 * - Server (API routes): Calls Egdesk API directly using EGDESK_CONFIG.apiUrl and
 *   EGDESK_CONFIG.apiKey (from env NEXT_PUBLIC_EGDESK_API_URL / NEXT_PUBLIC_EGDESK_API_KEY)
 *   so relative URLs and tunnel base path are not an issue.
 * - Client (browser): Uses /__user_data_proxy so CORS and tunnel base path still work.
 */
async function callUserDataTool(toolName, args = {}) {
    const body = JSON.stringify({ tool: toolName, arguments: args });
    const headers = {
        'Content-Type': 'application/json'
    };
    const isServer = typeof window === 'undefined';
    let response;
    if (isServer) {
        // API routes: call Egdesk directly (relative URL is invalid in Node)
        const apiUrl = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
            egdesk_config_1.EGDESK_CONFIG.apiUrl;
        const apiKey = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
            egdesk_config_1.EGDESK_CONFIG.apiKey;
        if (apiKey) {
            headers['X-Api-Key'] = apiKey;
        }
        response = await fetch(`${apiUrl}/user-data/tools/call`, {
            method: 'POST',
            headers,
            body
        });
    }
    else {
        // Browser: use proxy for CORS and tunnel base path
        response = await fetch('/__user_data_proxy', {
            method: 'POST',
            headers,
            body
        });
    }
    return parseEgdeskMcpToolResponse(response);
}
/**
 * Query table data
 */
async function queryTable(tableName, options = {}) {
    return callUserDataTool('user_data_query', {
        tableName,
        ...options
    });
}
/**
 * Search table
 */
async function searchTable(tableName, searchQuery, limit = 50) {
    return callUserDataTool('user_data_search', {
        tableName,
        searchQuery,
        limit
    });
}
/**
 * Aggregate data
 */
async function aggregateTable(tableName, column, aggregateFunction, options = {}) {
    return callUserDataTool('user_data_aggregate', {
        tableName,
        column,
        function: aggregateFunction,
        ...options
    });
}
/**
 * Execute raw SQL query (read-only, SELECT only)
 */
async function executeSQL(query) {
    return callUserDataTool('user_data_sql_query', { query });
}
/**
 * List all available tables
 */
async function listTables() {
    return callUserDataTool('user_data_list_tables', {});
}
/**
 * Get table schema
 */
async function getTableSchema(tableName) {
    return callUserDataTool('user_data_get_schema', { tableName });
}
/**
 * Create a new table
 */
async function createTable(displayName, schema, options) {
    return callUserDataTool('user_data_create_table', {
        displayName,
        schema,
        ...options
    });
}
/**
 * Insert rows into a table
 */
async function insertRows(tableName, rows) {
    return callUserDataTool('user_data_insert_rows', {
        tableName,
        rows
    });
}
/**
 * Update rows in a table
 */
async function updateRows(tableName, updates, options) {
    return callUserDataTool('user_data_update_rows', {
        tableName,
        updates,
        ...options
    });
}
/**
 * Delete rows from a table
 */
async function deleteRows(tableName, options) {
    return callUserDataTool('user_data_delete_rows', {
        tableName,
        ...options
    });
}
/**
 * Delete a table
 */
async function deleteTable(tableName) {
    return callUserDataTool('user_data_delete_table', { tableName });
}
/**
 * Rename a table
 */
async function renameTable(tableName, newTableName, newDisplayName) {
    return callUserDataTool('user_data_rename_table', {
        tableName,
        newTableName,
        newDisplayName
    });
}
// ==========================================
// FINANCEHUB HELPERS
// ==========================================
/**
 * Call EGDesk FinanceHub MCP tool
 */
async function callFinanceHubTool(toolName, args = {}) {
    const body = JSON.stringify({ tool: toolName, arguments: args });
    const headers = {
        'Content-Type': 'application/json'
    };
    const isServer = typeof window === 'undefined';
    let response;
    if (isServer) {
        const apiUrl = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
            egdesk_config_1.EGDESK_CONFIG.apiUrl;
        const apiKey = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
            egdesk_config_1.EGDESK_CONFIG.apiKey;
        if (apiKey) {
            headers['X-Api-Key'] = apiKey;
        }
        response = await fetch(`${apiUrl}/financehub/tools/call`, {
            method: 'POST',
            headers,
            body
        });
    }
    else {
        response = await fetch('/__financehub_proxy', {
            method: 'POST',
            headers,
            body
        });
    }
    return parseEgdeskMcpToolResponse(response);
}
/**
 * List all registered banks and card companies
 */
async function listBanks() {
    return callFinanceHubTool('financehub_list_banks', {});
}
/**
 * List bank accounts with balances
 */
async function listAccounts(options = {}) {
    return callFinanceHubTool('financehub_list_accounts', options);
}
/**
 * Query bank transactions
 */
async function queryBankTransactions(options = {}) {
    return callFinanceHubTool('financehub_query_transactions', options);
}
/**
 * Query card transactions (NEW)
 */
async function queryCardTransactions(options = {}) {
    return callFinanceHubTool('financehub_query_card_transactions', options);
}
/**
 * Get transaction statistics
 */
async function getTransactionStats(options = {}) {
    return callFinanceHubTool('financehub_get_statistics', options);
}
/**
 * Get monthly breakdown of deposits/withdrawals
 */
async function getMonthlySummary(options = {}) {
    return callFinanceHubTool('financehub_get_monthly_summary', options);
}
/**
 * Get overall stats (banks, accounts, transactions, balances)
 */
async function getOverallStats() {
    return callFinanceHubTool('financehub_get_overall_stats', {});
}
/**
 * Get bank/card sync operation history (sync_operations table)
 */
async function getSyncHistory(limit = 50) {
    return callFinanceHubTool('financehub_get_sync_history', { limit });
}
/**
 * List Hometax business connections (hometax_connections: counts, spreadsheet URLs, status)
 */
async function listHometaxConnections() {
    return callFinanceHubTool('financehub_list_hometax_connections', {});
}
/**
 * Query electronic tax invoices synced from Hometax (tax_invoices table)
 */
async function queryTaxInvoices(options = {}) {
    return callFinanceHubTool('financehub_query_tax_invoices', options);
}
/**
 * Query tax-exempt invoices synced from Hometax (tax_exempt_invoices table)
 */
async function queryTaxExemptInvoices(options = {}) {
    return callFinanceHubTool('financehub_query_tax_exempt_invoices', options);
}
/**
 * Query cash receipts synced from Hometax (cash_receipts table)
 */
async function queryCashReceipts(options = {}) {
    return callFinanceHubTool('financehub_query_cash_receipts', options);
}
/**
 * Get Hometax Excel import sync history (hometax_sync_operations). Not the same as getSyncHistory (banks/cards).
 */
async function getHometaxSyncHistory(limit = 50) {
    return callFinanceHubTool('financehub_get_hometax_sync_history', { limit });
}
/**
 * List per-(bank, product) bank-product tables — bank-side product data
 * downloaded from bank portals that isn't core deposit/card transactions
 * (loans, receivables, e-bills, etc.). Returns table slugs, displayName,
 * column schemas, and row counts. ALWAYS call this first to discover
 * what tables exist before calling queryBankProductTable.
 */
async function listBankProductTables() {
    return callFinanceHubTool('financehub_list_bank_product_tables', {});
}
/**
 * Generic safe query against any per-(bank, product) table from
 * listBankProductTables. Filters use the table's exact column names
 * (snake_case). Returns rows with totalMatching, limit, offset.
 *
 * @example
 *   queryBankProductTable({
 *     tableSlug: 'ibk_loan_transactions',
 *     filters: [
 *       { column: 'account_number', op: '=', value: '306-063568-04-036' },
 *       { column: 'transaction_amount', op: '>', value: 1000000 },
 *     ],
 *     orderBy: { column: 'transaction_date', direction: 'DESC' },
 *     limit: 50,
 *   });
 */
async function queryBankProductTable(options) {
    return callFinanceHubTool('financehub_query_bank_product_table', options);
}
/**
 * Create or update a bank/card account (no credentials).
 */
async function upsertFinanceHubAccount(account) {
    return callFinanceHubTool('financehub_upsert_account', account);
}
/**
 * Import bank or card transactions (deduplicated). Max 1000 per call.
 */
async function importFinanceHubTransactions(options) {
    return callFinanceHubTool('financehub_import_transactions', options);
}
/**
 * Upsert rows into a bank-product table (loans, receivables, etc.). Max 500 per call.
 */
async function upsertFinanceHubBankProductRows(options) {
    return callFinanceHubTool('financehub_upsert_bank_product_rows', options);
}
/**
 * Delete an account and all its transactions/sync rows (not credentials).
 */
async function deleteFinanceHubAccount(bankId, accountNumber) {
    return callFinanceHubTool('financehub_delete_account', { bankId, accountNumber });
}
/**
 * Delete all imported data for a bankId (accounts, transactions, sync ops).
 */
async function deleteFinanceHubImportedDataForBank(bankId) {
    return callFinanceHubTool('financehub_delete_imported_data_for_bank', { bankId });
}
/**
 * Delete transactions by account scope, date range, and/or ids (max 500 ids).
 */
async function deleteFinanceHubTransactions(options) {
    return callFinanceHubTool('financehub_delete_transactions', options);
}
/**
 * Delete bank-product table rows by ids and/or filters (max 1000 rows).
 */
async function deleteFinanceHubBankProductRows(options) {
    return callFinanceHubTool('financehub_delete_bank_product_rows', options);
}
// ==========================================
// INTERNAL KNOWLEDGE / BUSINESS IDENTITY / COMPANY RESEARCH (MCP)
// ==========================================
/**
 * Call EGDesk Internal Knowledge MCP tool (knowledge docs, business identity snapshots, company research).
 *
 * - Server: `POST {apiUrl}/internal-knowledge/tools/call`
 * - Client: `POST /__internal_knowledge_proxy` (see proxy.ts / middleware)
 */
async function callInternalKnowledgeTool(toolName, args = {}) {
    const body = JSON.stringify({ tool: toolName, arguments: args });
    const headers = {
        'Content-Type': 'application/json'
    };
    const isServer = typeof window === 'undefined';
    let response;
    if (isServer) {
        const apiUrl = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
            egdesk_config_1.EGDESK_CONFIG.apiUrl;
        const apiKey = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
            egdesk_config_1.EGDESK_CONFIG.apiKey;
        if (apiKey) {
            headers['X-Api-Key'] = apiKey;
        }
        response = await fetch(`${apiUrl}/internal-knowledge/tools/call`, {
            method: 'POST',
            headers,
            body
        });
    }
    else {
        response = await fetch('/__internal_knowledge_proxy', {
            method: 'POST',
            headers,
            body
        });
    }
    return parseEgdeskMcpToolResponse(response);
}
/** List internal knowledge documents for a business identity snapshot */
async function listKnowledgeDocuments(snapshotId, category) {
    return callInternalKnowledgeTool('knowledge_list_documents', {
        snapshotId,
        ...(category != null ? { category } : {})
    });
}
/** Get one knowledge document by ID (full markdown content) */
async function getKnowledgeDocument(documentId) {
    return callInternalKnowledgeTool('knowledge_get_document', { documentId });
}
/** Search knowledge documents by text in title or content */
async function searchKnowledgeContent(snapshotId, searchText, category) {
    return callInternalKnowledgeTool('knowledge_search_content', {
        snapshotId,
        searchText,
        ...(category != null ? { category } : {})
    });
}
/** Get all documents of a single category for a snapshot */
async function getKnowledgeByCategory(snapshotId, category) {
    return callInternalKnowledgeTool('knowledge_get_by_category', { snapshotId, category });
}
/** Create a new knowledge document */
async function createKnowledgeDocument(snapshotId, title, category, content) {
    return callInternalKnowledgeTool('knowledge_create_document', {
        snapshotId,
        title,
        category,
        ...(content != null ? { content } : {})
    });
}
/** Update an existing knowledge document */
async function updateKnowledgeDocument(documentId, updates) {
    return callInternalKnowledgeTool('knowledge_update_document', { documentId, ...updates });
}
/** Delete a knowledge document */
async function deleteKnowledgeDocument(documentId) {
    return callInternalKnowledgeTool('knowledge_delete_document', { documentId });
}
/** List business identity snapshots (optional brand filter) */
async function listBusinessIdentitySnapshots(brandKey) {
    return callInternalKnowledgeTool('businessidentity_list_snapshots', {
        ...(brandKey != null ? { brandKey } : {})
    });
}
/** Full snapshot by ID (identity JSON, SEO/SSL analysis, etc.) */
async function getBusinessIdentitySnapshot(snapshotId) {
    return callInternalKnowledgeTool('businessidentity_get_snapshot', { snapshotId });
}
/** Company info slice from a snapshot (contact, structure, partners, industries) */
async function getBusinessIdentityCompanyInfo(snapshotId) {
    return callInternalKnowledgeTool('businessidentity_get_company_info', { snapshotId });
}
/** Services and products from a snapshot */
async function getBusinessIdentityServicesProducts(snapshotId) {
    return callInternalKnowledgeTool('businessidentity_get_services_products', { snapshotId });
}
/** List company research records */
async function listCompanyResearch(status) {
    return callInternalKnowledgeTool('companyresearch_list_all', {
        ...(status != null ? { status } : {})
    });
}
/** One company research record by ID */
async function getCompanyResearchById(researchId) {
    return callInternalKnowledgeTool('companyresearch_get_by_id', { researchId });
}
/** Research records for a domain */
async function getCompanyResearchByDomain(domain) {
    return callInternalKnowledgeTool('companyresearch_get_by_domain', { domain });
}
/** Search company research by company name or domain */
async function searchCompanyResearch(searchText) {
    return callInternalKnowledgeTool('companyresearch_search', { searchText });
}
// ==========================================
// BROWSER RECORDING HELPERS
// ==========================================
/**
 * Call EGDesk Browser Recording MCP tool (saved recorder tests, replay with optional dates).
 *
 * - Server: `POST {apiUrl}/browser-recording/tools/call`
 * - Client: `POST /__browser_recording_proxy` (see proxy.ts / middleware)
 */
async function callBrowserRecordingTool(toolName, args = {}) {
    const body = JSON.stringify({ tool: toolName, arguments: args });
    const headers = {
        'Content-Type': 'application/json'
    };
    const isServer = typeof window === 'undefined';
    let response;
    if (isServer) {
        const apiUrl = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
            egdesk_config_1.EGDESK_CONFIG.apiUrl;
        const apiKey = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
            egdesk_config_1.EGDESK_CONFIG.apiKey;
        if (apiKey) {
            headers['X-Api-Key'] = apiKey;
        }
        response = await fetch(`${apiUrl}/browser-recording/tools/call`, {
            method: 'POST',
            headers,
            body
        });
    }
    else {
        response = await fetch('/__browser_recording_proxy', {
            method: 'POST',
            headers,
            body
        });
    }
    return parseEgdeskMcpToolResponse(response);
}
/** List saved *.spec.js files in the EGDesk browser-recorder-tests output folder */
async function listBrowserRecordingTests() {
    return callBrowserRecordingTool('browser_recording_list_saved_tests', {});
}
/** Inspect a spec: date UI, defaultReplayDates, labeledFieldReplayBlocks, etc. */
async function getBrowserRecordingReplayOptions(testFile) {
    return callBrowserRecordingTool('browser_recording_get_replay_options', { testFile });
}
/** Replay a saved recording in Chrome (optional headless, dates + labeledFieldFills) */
async function runBrowserRecording(testFile, options = {}) {
    return callBrowserRecordingTool('browser_recording_run', {
        testFile,
        ...options
    });
}
/** List Playwright scheduler entries for browser recorder tests */
async function listBrowserRecordingSchedules() {
    return callBrowserRecordingTool('browser_recording_list_schedules', {});
}
/** Get schedule for a test file, or null */
async function getBrowserRecordingSchedule(testFile) {
    return callBrowserRecordingTool('browser_recording_get_schedule', { testFile });
}
/** Create or update a recurring schedule for a saved test */
async function setBrowserRecordingSchedule(testFile, options = {}) {
    return callBrowserRecordingTool('browser_recording_set_schedule', {
        testFile,
        ...options
    });
}
/** Remove scheduler entry for a test file */
async function removeBrowserRecordingSchedule(testFile) {
    return callBrowserRecordingTool('browser_recording_remove_schedule', { testFile });
}
/** Pause a recurring schedule without deleting it */
async function pauseBrowserRecordingSchedule(testFile) {
    return callBrowserRecordingTool('browser_recording_pause_schedule', { testFile });
}
/** Resume a paused recurring schedule */
async function resumeBrowserRecordingSchedule(testFile) {
    return callBrowserRecordingTool('browser_recording_resume_schedule', { testFile });
}
/** List EGDesk-Browser download folders with Excel/CSV files */
async function listBrowserRecordingDownloadFolders() {
    return callBrowserRecordingTool('browser_recording_list_download_folders', {});
}
/** List sync-to-SQL configs for browser downloads */
async function listBrowserRecordingSyncConfigs() {
    return callBrowserRecordingTool('browser_recording_list_sync_configs', {});
}
/** Get sync config by testFile or scriptFolderPath */
async function getBrowserRecordingSyncConfig(opts) {
    return callBrowserRecordingTool('browser_recording_get_sync_config', opts);
}
/** Create or update sync-to-DB for a browser download folder */
async function setBrowserRecordingSyncConfig(opts) {
    return callBrowserRecordingTool('browser_recording_set_sync_config', opts);
}
/** Remove sync config by configId, testFile, or scriptFolderPath */
async function removeBrowserRecordingSyncConfig(opts) {
    return callBrowserRecordingTool('browser_recording_remove_sync_config', opts);
}
// ==========================================
// AI CENTER (workflows, entities, relations, tags)
// ==========================================
/**
 * Call EGDesk AI Center MCP tool (workflows, Neuron Layer entities/relations/tags).
 *
 * - Server: `POST {apiUrl}/ai-center/tools/call`
 * - Client: `POST /__ai_center_proxy` (see proxy.ts / middleware)
 */
async function callAICenterTool(toolName, args = {}) {
    const body = JSON.stringify({ tool: toolName, arguments: args });
    const headers = {
        'Content-Type': 'application/json'
    };
    const isServer = typeof window === 'undefined';
    let response;
    if (isServer) {
        const apiUrl = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
            egdesk_config_1.EGDESK_CONFIG.apiUrl;
        const apiKey = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
            egdesk_config_1.EGDESK_CONFIG.apiKey;
        if (apiKey) {
            headers['X-Api-Key'] = apiKey;
        }
        response = await fetch(`${apiUrl}/ai-center/tools/call`, {
            method: 'POST',
            headers,
            body
        });
    }
    else {
        response = await fetch('/__ai_center_proxy', {
            method: 'POST',
            headers,
            body
        });
    }
    return parseEgdeskMcpToolResponse(response);
}
// ── Data Sources ─────────────────────────────────────────────────────────────
/**
 * List all data sources available for AI processing (user data tables, finance hub accounts,
 * business identity snapshots, company research records) with processing state.
 */
async function listDataSources() {
    return callAICenterTool('ai_center_list_data_sources', {});
}
// ── Workflows ────────────────────────────────────────────────────────────────
/** List all AI workflows */
async function listWorkflows() {
    return callAICenterTool('ai_center_list_workflows', {});
}
/** Get a single workflow by ID (includes action steps) */
async function getWorkflow(id) {
    return callAICenterTool('ai_center_get_workflow', { id });
}
/** Create a new AI workflow */
async function createWorkflow(data) {
    return callAICenterTool('ai_center_create_workflow', data);
}
/** Update metadata fields of an existing workflow */
async function updateWorkflow(id, data) {
    return callAICenterTool('ai_center_update_workflow', { id, ...data });
}
/** Change the status of a workflow */
async function updateWorkflowStatus(id, status) {
    return callAICenterTool('ai_center_update_workflow_status', { id, status });
}
/** Delete a workflow and all its action steps */
async function deleteWorkflow(id) {
    return callAICenterTool('ai_center_delete_workflow', { id });
}
// ── Workflow notify roles ─────────────────────────────────────────────────────
/** Set which roles receive notifications for all activity on a workflow's runs */
async function setWorkflowNotifyRoles(workflowId, roles) {
    return callAICenterTool('ai_center_set_workflow_notify', { workflowId, roles });
}
// ── Workflow actions ──────────────────────────────────────────────────────────
/** Append or insert an action step into a workflow */
async function addWorkflowAction(workflowId, actionId, params, stage = 0, position = 0) {
    return callAICenterTool('ai_center_add_workflow_action', { workflowId, actionId, params, stage, position });
}
/** Remove a single action step from a workflow by its row ID */
async function removeWorkflowAction(rowId) {
    return callAICenterTool('ai_center_remove_workflow_action', { rowId });
}
// ── Workflow runs ─────────────────────────────────────────────────────────────
/** Start a new run of a workflow, optionally linked to a source data row */
async function createRun(workflowId, inputData, sourceTable, sourceRowId) {
    return callAICenterTool('ai_center_create_run', { workflowId, inputData, sourceTable, sourceRowId });
}
/** Get a single workflow run by ID */
async function getRun(runId) {
    return callAICenterTool('ai_center_get_run', { runId });
}
/** Get all runs for a workflow */
async function getRuns(workflowId) {
    return callAICenterTool('ai_center_get_runs', { workflowId });
}
/** Update the status of a workflow run */
async function updateRunStatus(runId, status) {
    return callAICenterTool('ai_center_update_run_status', { runId, status });
}
/** Advance a workflow run to a new stage */
async function advanceRunStage(runId, stage) {
    return callAICenterTool('ai_center_advance_run_stage', { runId, stage });
}
// ── Workflow approvals ────────────────────────────────────────────────────────
/** Create a pending approval record for a run */
async function createApproval(runId, stage, chainPosition, role) {
    return callAICenterTool('ai_center_create_approval', { runId, stage, chainPosition, role });
}
/** Get all approval records for a run */
async function getApprovals(runId) {
    return callAICenterTool('ai_center_get_approvals', { runId });
}
/** Record an approval decision */
async function recordApprovalDecision(approvalId, decision) {
    return callAICenterTool('ai_center_record_approval_decision', { approvalId, decision });
}
// ── Entities ──────────────────────────────────────────────────────────────────
/** List all Neuron Layer entities, optionally filtered by type */
async function listEntities(types) {
    return callAICenterTool('ai_center_list_entities', types ? { types } : {});
}
/** Create a new entity in the Neuron Layer */
async function createEntity(data) {
    return callAICenterTool('ai_center_create_entity', data);
}
/** Delete an entity from the Neuron Layer */
async function deleteEntity(id) {
    return callAICenterTool('ai_center_delete_entity', { id });
}
// ── Relations ─────────────────────────────────────────────────────────────────
/** List all relations, optionally filtered by source entity ID */
async function listRelations(fromId) {
    return callAICenterTool('ai_center_list_relations', fromId ? { fromId } : {});
}
/** Create a relation edge between two entities */
async function createRelation(data) {
    return callAICenterTool('ai_center_create_relation', data);
}
/** Delete a relation edge by ID */
async function deleteRelation(id) {
    return callAICenterTool('ai_center_delete_relation', { id });
}
// ── Tags ──────────────────────────────────────────────────────────────────────
/** List all tags, optionally filtered by entity ID */
async function listTags(entityId) {
    return callAICenterTool('ai_center_list_tags', entityId ? { entityId } : {});
}
/** Create a tag/property on an entity or document */
async function createTag(data) {
    return callAICenterTool('ai_center_create_tag', data);
}
/** Delete a tag by ID */
async function deleteTag(id) {
    return callAICenterTool('ai_center_delete_tag', { id });
}
/** List all company-wide shared business deadlines from the company calendar (company_calendar table). */
async function getCalendarEventsFromAICenter() {
    return callAICenterTool('ai_center_get_calendar_events', {});
}
/** Update the status of an operational task. */
async function completeTask(taskId, status) {
    return callAICenterTool('ai_center_complete_task', { taskId, status });
}
// ==========================================
// KOREAN LAW / LAWYER (MCP)
// ==========================================
/**
 * Call EGDesk Korean Law MCP tool (법제처 API — laws, precedents, admin rules, municipal ordinances).
 *
 * - Server: `POST {apiUrl}/korean-law/tools/call`
 * - Client: `POST /__korean_law_proxy` (see proxy.ts / middleware)
 */
async function callKoreanLawTool(toolName, args = {}) {
    const body = JSON.stringify({ tool: toolName, arguments: args });
    const headers = {
        'Content-Type': 'application/json'
    };
    const isServer = typeof window === 'undefined';
    let response;
    if (isServer) {
        const apiUrl = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_URL) ||
            egdesk_config_1.EGDESK_CONFIG.apiUrl;
        const apiKey = (typeof process !== 'undefined' && process.env?.NEXT_PUBLIC_EGDESK_API_KEY) ||
            egdesk_config_1.EGDESK_CONFIG.apiKey;
        if (apiKey) {
            headers['X-Api-Key'] = apiKey;
        }
        response = await fetch(`${apiUrl}/korean-law/tools/call`, {
            method: 'POST',
            headers,
            body
        });
    }
    else {
        response = await fetch('/__korean_law_proxy', {
            method: 'POST',
            headers,
            body
        });
    }
    return parseEgdeskMcpToolResponse(response);
}
/** Search laws, precedents, administrative rules, or municipal ordinances */
async function searchKoreanLaw(query, options = {}) {
    return callKoreanLawTool('korean_law_search', { query, ...options });
}
/** Get full text of a law, administrative rule, or municipal ordinance */
async function getKoreanLawText(id, target = 'law') {
    return callKoreanLawTool('korean_law_get_text', { id, target });
}
/** Get full text of a court precedent (판례) */
async function getKoreanLawDecision(id) {
    return callKoreanLawTool('korean_law_get_decision', { id });
}
