import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * EGDesk Database Proxy (Next.js 16+)
 *
 * Intercepts __user_data_proxy, __browser_recording_proxy, __internal_knowledge_proxy, __company_research_proxy, __ai_center_proxy, __korean_law_proxy, __seo_proxy, __ssl_proxy, __local_agent_proxy, __pageindex_proxy, __egdesk_config_proxy, __ai_caller_proxy, and __kakao_proxy requests
 * and forwards them to the EGDesk MCP HTTP server. This avoids CORS in local and tunneled environments.
 *
 * Generated by @egdesk/next-api-plugin
 */

/** Build EGDesk routing headers from env vars (injected into every upstream call). */
function buildEgdeskHeaders(): Record<string, string> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  const apiKey = process.env.NEXT_PUBLIC_EGDESK_API_KEY;
  const projectId = process.env.NEXT_PUBLIC_EGDESK_PROJECT_ID;
  const egdeskEnv = process.env.NEXT_PUBLIC_EGDESK_ENV;
  if (apiKey) headers['X-Api-Key'] = apiKey;
  if (projectId) headers['X-EGDesk-Project-Id'] = projectId;
  if (egdeskEnv) headers['X-EGDesk-Env'] = egdeskEnv;
  return headers;
}

export async function proxy(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Intercept __user_data_proxy requests
  if (pathname.includes('__user_data_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      // Forward to EGDesk MCP server
      const response = await fetch(`${apiUrl}/user-data/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__browser_recording_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/browser-recording/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__internal_knowledge_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/internal-knowledge/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__ai_center_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/ai-center/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__korean_law_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/korean-law/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__seo_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/seo/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__ssl_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/ssl/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__company_research_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/company-research/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__local_agent_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/local-agent/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__pageindex_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/pageindex/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__kakao_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/kakao/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__egdesk_config_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/egdesk-config/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  if (pathname.includes('__ai_caller_proxy')) {
    try {
      const body = await request.text();
      const apiUrl = process.env.NEXT_PUBLIC_EGDESK_API_URL || 'http://localhost:8080';

      const response = await fetch(`${apiUrl}/ai-caller/tools/call`, {
        method: 'POST',
        headers: buildEgdeskHeaders(),
        body,
      });

      const result = await response.json();

      return NextResponse.json(result, { status: response.status });
    } catch (error: any) {
      return NextResponse.json(
        { error: 'Proxy error', message: error.message },
        { status: 500 }
      );
    }
  }

  // 🛡️ 로그인 인증 리다이렉션 가드
  const isPublicRoute =
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    pathname === '/login' ||
    pathname.startsWith('/m/') || 
    pathname === '/m' ||
    pathname.startsWith('/public/') ||
    pathname.includes('favicon.ico');

  const token = request.cookies.get('auth_token')?.value;

  // 비로그인 사용자가 보호된 경로 접근 시 -> 로그인으로 리다이렉트
  if (!token && !isPublicRoute) {
    const loginUrl = new URL('/login', request.url);
    return NextResponse.redirect(loginUrl);
  }

  // 이미 로그인한 사용자가 로그인 페이지 접근 시 -> 메인 대시보드로 리다이렉트
  if (token && pathname === '/login') {
    const dashboardUrl = new URL('/', request.url);
    return NextResponse.redirect(dashboardUrl);
  }

  // Continue to next proxy or route
  return NextResponse.next();
}

export const config = {
  matcher: [
    /*
     * Match all paths except static assets
     * The proxy function filters for __user_data_proxy / __browser_recording_proxy / __internal_knowledge_proxy / __company_research_proxy / __ai_center_proxy / __korean_law_proxy / __seo_proxy / __ssl_proxy / __local_agent_proxy / __pageindex_proxy / __egdesk_config_proxy / __ai_caller_proxy / __kakao_proxy
     */
    '/:path*',
  ],
};
